
import { Exercise } from './types.ts';

/**
 * PHYSIOCORE MASTER CLINICAL LIBRARY v10.0
 * 7 Categories x 10 Exercises = 70 Professional Records
 * All UUIDs are Postgres compliant.
 */
export const SEED_EXERCISES: Exercise[] = [
  // ==========================================
  // 1. SPINE (OMURGA) - 10 ITEMS
  // ==========================================
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d471', code: 'SP-01', title: 'McKenzie Prone Press-up', titleTr: 'McKenzie Yüzüstü Doğrulma',
    category: 'Spine', difficulty: 3, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion',
    description: 'Yüzüstü yatın, kollarınızla gövdenizi kalçayı yerden ayırmadan yukarı itin.',
    biomechanics: 'L4-L5 segmentinde distraksiyon ve disk santralizasyonu sağlar.',
    safetyFlags: ['Spondylolisthesis'], equipment: ['Mat'], primaryMuscles: ['Erector Spinae'],
    rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-2-2', secondaryMuscles: [], isMotion: true, targetRpe: 5
  },
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d472', code: 'SP-02', title: 'Bird-Dog Stability', titleTr: 'Çapraz Kol-Bacak Uzatma',
    category: 'Spine', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'X-Ray',
    description: 'Dört ayak üzerinde çapraz kol ve bacağınızı aynı anda uzatın.',
    biomechanics: 'Multifidus aktivasyonu ve core stabilitesi sağlar.',
    safetyFlags: ['Denge Kaybı'], equipment: ['Mat'], primaryMuscles: ['Multifidus'],
    rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 5
  },
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d473', code: 'SP-03', title: 'Pelvic Tilts', titleTr: 'Pelvik Tilt',
    category: 'Spine', difficulty: 2, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'Schematic',
    description: 'Sırtüstü yatarken bel çukurunu yere bastırıp bırakın.',
    biomechanics: 'Lomber mobilizasyon ve pelvik kontrol.',
    safetyFlags: ['Akut Ağrı'], equipment: ['Mat'], primaryMuscles: ['Abs'],
    rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-0-2', secondaryMuscles: [], isMotion: true, targetRpe: 3
  },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d474', code: 'SP-04', title: 'Chin Tucks', titleTr: 'Boyun Geri Çekme', category: 'Spine', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Çeneyi arkaya çekerek boyun kaslarını aktifleyin.', biomechanics: 'Deep Neck Flexors activation.', safetyFlags: ['Vertigo'], equipment: ['Yok'], primaryMuscles: ['Longus Colli'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '5-2-5', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d475', code: 'SP-05', title: 'Cat-Camel', titleTr: 'Kedi-Deve', category: 'Spine', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: '4K-Render', description: 'Sırtınızı yukarı ve aşağı hareket ettirin.', biomechanics: 'Segmental mobility.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Spinals'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '4-0-4', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d476', code: 'SP-06', title: 'Thoracic Rotation', titleTr: 'Sırt Rotasyonu', category: 'Spine', difficulty: 4, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Yan yatarken üstteki kolu geriye doğru açın.', biomechanics: 'Thoracic mobility improvement.', safetyFlags: ['Kaburga Hassasiyeti'], equipment: ['Mat'], primaryMuscles: ['Thoracic Spine'], rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '3-2-3', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d477', code: 'SP-07', title: 'Wall Slides', titleTr: 'Duvarda Kol Kaydırma', category: 'Spine', difficulty: 5, sets: 3, reps: 12, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Sırtınız duvarda kollarınızı yukarı aşağı kaydırın.', biomechanics: 'Scapular stability.', safetyFlags: ['Omuz İmpingement'], equipment: ['Duvar'], primaryMuscles: ['Trapezius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: '3-0-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d478', code: 'SP-08', title: 'Bridges', titleTr: 'Köprü Kurma', category: 'Spine', difficulty: 3, sets: 3, reps: 15, restPeriod: 45, visualStyle: 'X-Ray', description: 'Sırtüstü yatarken kalçanızı yukarı kaldırın.', biomechanics: 'Gluteal activation and lumbar stability.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Gluteus Maximus'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479', code: 'SP-09', title: 'Side-lying Rotation', titleTr: 'Yana Yatış Rotasyon', category: 'Spine', difficulty: 3, sets: 2, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Gövdeyi sabit tutup üst kolu geriye uzatın.', biomechanics: 'Functional mobility.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Obliques'], rehabPhase: 'Akut', movementPlane: 'Transverse', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d480', code: 'SP-10', title: 'Supermans', titleTr: 'Süpermen Egzersizi', category: 'Spine', difficulty: 6, sets: 3, reps: 10, restPeriod: 60, visualStyle: '4K-Render', description: 'Yüzüstü kol ve bacakları aynı anda kaldırın.', biomechanics: 'Posterior chain strengthening.', safetyFlags: ['Stenoz'], equipment: ['Mat'], primaryMuscles: ['Lower Back'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '2-2-2', secondaryMuscles: [], isMotion: true, targetRpe: 7 },

  // ==========================================
  // 2. LOWER LIMB (ALT EKSTREMİTE) - 10 ITEMS
  // ==========================================
  { id: '6ba7b810-9dad-11d1-80b4-00c04fd430c8', code: 'LL-01', title: 'Terminal Knee Extension', titleTr: 'Terminal Diz Ekstansiyonu', category: 'Lower Limb', difficulty: 3, sets: 3, reps: 15, restPeriod: 30, visualStyle: '4K-Render', description: 'Direnç bandıyla dizinizi tam düzleştirin.', biomechanics: 'VMO activation.', safetyFlags: [], equipment: ['Direnç Bandı'], primaryMuscles: ['VMO'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '1-2-1', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '6ba7b810-9dad-11d1-80b4-00c04fd430c9', code: 'LL-02', title: 'Clamshells', titleTr: 'İstiridye', category: 'Lower Limb', difficulty: 4, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Yan yatışta üstteki dizi açın.', biomechanics: 'Gluteus Medius activation.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Gluteus Medius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '6ba7b810-9dad-11d1-80b4-00c04fd430d0', code: 'LL-03', title: 'Wall Squat (Static)', titleTr: 'Duvarda Squat (Statik)', category: 'Lower Limb', difficulty: 5, sets: 3, reps: 45, restPeriod: 60, visualStyle: 'X-Ray', description: 'Duvarda 90 derece diz açısıyla bekleyin.', biomechanics: 'Isometric quad strength.', safetyFlags: ['PFPS'], equipment: ['Duvar'], primaryMuscles: ['Quadriceps'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Static', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d1', code: 'LL-04', title: 'Heel Slides', titleTr: 'Topuk Kaydırma', category: 'Lower Limb', difficulty: 1, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'Schematic', description: 'Sırtüstü topuğunuzu kalçaya doğru kaydırın.', biomechanics: 'Knee ROM.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Hamstrings'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '3-0-3', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d2', code: 'LL-05', title: 'Calf Raises', titleTr: 'Parmak Ucuna Yükselme', category: 'Lower Limb', difficulty: 3, sets: 3, reps: 20, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Ayakta parmak ucuna yükselin.', biomechanics: 'Gastroc/Soleus strength.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Gastrocnemius'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '1-0-1', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d3', code: 'LL-06', title: 'Straight Leg Raise', titleTr: 'Düz Bacak Kaldırma', category: 'Lower Limb', difficulty: 3, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'X-Ray', description: 'Bacağınızı düz tutarak 45 derece kaldırın.', biomechanics: 'Hip flexor/Quad isolation.', safetyFlags: ['Bel Ağrısı'], equipment: ['Mat'], primaryMuscles: ['Rectus Femoris'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d4', code: 'LL-07', title: 'Hamstring Curls (Band)', titleTr: 'Hamstring Curl (Bantla)', category: 'Lower Limb', difficulty: 4, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Yüzüstü bandın direncine karşı dizi bükün.', biomechanics: 'Posterior chain strength.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Hamstrings'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '2-0-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d5', code: 'LL-08', title: 'Side Leg Raises', titleTr: 'Yana Bacak Açma', category: 'Lower Limb', difficulty: 4, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Yan yatışta bacağı yana kaldırın.', biomechanics: 'Hip abductor strength.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Gluteus Medius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d6', code: 'LL-09', title: 'Lunges (Static)', titleTr: 'Statik Lunge', category: 'Lower Limb', difficulty: 6, sets: 3, reps: 10, restPeriod: 60, visualStyle: '4K-Render', description: 'Bir adım önde diz çökme pozisyonuna inin.', biomechanics: 'Eccentric control and balance.', safetyFlags: ['Diz Kapağı Hassasiyeti'], equipment: ['Yok'], primaryMuscles: ['Quadriceps', 'Glutes'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d7', code: 'LL-10', title: 'Ankle Pumps', titleTr: 'Ayak Bileği Pompası', category: 'Lower Limb', difficulty: 1, sets: 3, reps: 20, restPeriod: 20, visualStyle: 'Schematic', description: 'Ayak bileğinizi ileri geri hareket ettirin.', biomechanics: 'Venous return / Circulatory support.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Calves'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '1-0-1', secondaryMuscles: [], isMotion: true, targetRpe: 1 },

  // ==========================================
  // 3. UPPER LIMB (ÜST EKSTREMİTE) - 10 ITEMS
  // ==========================================
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a1', code: 'UL-01', title: 'Pendulum Swings', titleTr: 'Pendulum (Sarkaç)', category: 'Upper Limb', difficulty: 1, sets: 3, reps: 60, restPeriod: 30, visualStyle: 'Schematic', description: 'Öne eğilip kolunuzu sarkaç gibi sallayın.', biomechanics: 'Passive joint distraction.', safetyFlags: [], equipment: ['Sandalye'], primaryMuscles: ['Shoulder Capsule'], rehabPhase: 'Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a2', code: 'UL-02', title: 'Scapular Squeezes', titleTr: 'Skapuler Sıkıştırma', category: 'Upper Limb', difficulty: 2, sets: 3, reps: 12, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Kürek kemiklerini birbirine yaklaştırın.', biomechanics: 'Rhomboid activation.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Rhomboids'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: '3-3-3', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a3', code: 'UL-03', title: 'External Rotation (Band)', titleTr: 'Dış Rotasyon (Bant)', category: 'Upper Limb', difficulty: 4, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'X-Ray', description: 'Dirsek gövdede bandı dışa çekin.', biomechanics: 'Rotator cuff stabilization.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Infraspinatus'], rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a4', code: 'UL-04', title: 'Wall Push-ups', titleTr: 'Duvarda Şınav', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 10, restPeriod: 45, visualStyle: '4K-Render', description: 'Elleriniz duvarda şınav çekin.', biomechanics: 'Pectoral strength with stability.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Pectoralis Major'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a5', code: 'UL-05', title: 'Bicep Curls (Band)', titleTr: 'Bicep Curl (Bant)', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Bandın üzerine basıp kollarınızı bükün.', biomechanics: 'Elbow flexor strength.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Biceps Brachii'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '2-0-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a6', code: 'UL-06', title: 'Tricep Extensions', titleTr: 'Triceps Ekstansiyon', category: 'Upper Limb', difficulty: 4, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Bandı tavandan aşağı doğru çekin.', biomechanics: 'Elbow extensor isolation.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Triceps'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a7', code: 'UL-07', title: 'Shoulder Flexion', titleTr: 'Omuz Fleksiyonu', category: 'Upper Limb', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'X-Ray', description: 'Kolunuzu öne doğru tavana kaldırın.', biomechanics: 'Anterior deltoid activation.', safetyFlags: ['Painful Arc'], equipment: ['Yok'], primaryMuscles: ['Deltoid'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-0-3', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a8', code: 'UL-08', title: 'Serratus Punch', titleTr: 'Serratus Yumruğu', category: 'Upper Limb', difficulty: 4, sets: 3, reps: 15, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Sırtüstü kollarınızı tavana doğru "yumruklayın".', biomechanics: 'Scapular protraction.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Serratus Anterior'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '1-2-1', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a9', code: 'UL-09', title: 'Wrist Stretches', titleTr: 'El Bileği Esnetme', category: 'Upper Limb', difficulty: 1, sets: 2, reps: 30, restPeriod: 20, visualStyle: 'Schematic', description: 'Diğer elinizle bileğinizi geriye çekin.', biomechanics: 'Flexor/Extensor lengthening.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Wrist Flexors'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Static', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430b0', code: 'UL-10', title: 'Finger Glimmers', titleTr: 'Parmak Egzersizleri', category: 'Upper Limb', difficulty: 1, sets: 3, reps: 20, restPeriod: 20, visualStyle: '4K-Render', description: 'Parmaklarınızı tek tek açıp kapatın.', biomechanics: 'Fine motor coordination.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Intrinsic Hand'], rehabPhase: 'Akut', movementPlane: 'Combined', tempo: '1-0-1', secondaryMuscles: [], isMotion: true, targetRpe: 1 },

  // ==========================================
  // 4. STABILITY (STABİLİZASYON) - 10 ITEMS
  // ==========================================
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c1', code: 'ST-01', title: 'Forearm Plank', titleTr: 'Plank', category: 'Stability', difficulty: 7, sets: 3, reps: 30, restPeriod: 60, visualStyle: '4K-Render', description: 'Dirsekler üzerinde tüm vücudu düz tutun.', biomechanics: 'Isometric core co-contraction.', safetyFlags: ['Bel Çukuru Bozulması'], equipment: ['Mat'], primaryMuscles: ['Rectus Abdominis'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c2', code: 'ST-02', title: 'Dead Bug', titleTr: 'Dead Bug', category: 'Stability', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'X-Ray', description: 'Sırtüstü çapraz kol-bacak açın.', biomechanics: 'Lumbopelvik stabilite.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Transversus Abdominis'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-0-3', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c3', code: 'ST-03', title: 'Single Leg Balance', titleTr: 'Tek Ayak Denge', category: 'Stability', difficulty: 4, sets: 3, reps: 30, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Tek ayak üzerinde sabit bekleyin.', biomechanics: 'Proprioception / Ankle stability.', safetyFlags: ['Düşme Riski'], equipment: ['Yok'], primaryMuscles: ['Ankle Stabilizers'], rehabPhase: 'Sub-Akut', movementPlane: 'Combined', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c4', code: 'ST-04', title: 'Side Plank', titleTr: 'Yan Plank', category: 'Stability', difficulty: 8, sets: 3, reps: 20, restPeriod: 60, visualStyle: '4K-Render', description: 'Yan yatıp kol üzerinde kalkın.', biomechanics: 'Lateral chain stability.', safetyFlags: ['Omuz Ağrısı'], equipment: ['Mat'], primaryMuscles: ['Obliques'], rehabPhase: 'Performans', movementPlane: 'Frontal', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 9 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c5', code: 'ST-05', title: 'Pallof Press', titleTr: 'Pallof Press', category: 'Stability', difficulty: 6, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Yan gelen bandı göğsünüzden ileri itin.', biomechanics: 'Anti-rotation core strength.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Core'], rehabPhase: 'Kronik', movementPlane: 'Transverse', tempo: '3-2-3', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c6', code: 'ST-06', title: 'Heel-to-Toe Walk', titleTr: 'Tandem Yürüyüş', category: 'Stability', difficulty: 3, sets: 2, reps: 20, restPeriod: 30, visualStyle: 'Schematic', description: 'Düz çizgide ayak ucu-topuk yürüyün.', biomechanics: 'Balance coordination.', safetyFlags: ['Denge Kaybı'], equipment: ['Yok'], primaryMuscles: ['Lower Limb'], rehabPhase: 'Sub-Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c7', code: 'ST-07', title: 'Bear Crawl (Static)', titleTr: 'Ayı Yürüyüşü (Statik)', category: 'Stability', difficulty: 7, sets: 3, reps: 30, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Dizler yere değmeden 4 ayak durun.', biomechanics: 'Full body co-contraction.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Core', 'Shoulders'], rehabPhase: 'Performans', movementPlane: 'Combined', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c8', code: 'ST-08', title: 'Glute Bridge (Single)', titleTr: 'Tek Ayak Köprü', category: 'Stability', difficulty: 6, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'X-Ray', description: 'Tek ayak yerdeyken köprü yapın.', biomechanics: 'Asymmetric glute strength.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Gluteus Maximus'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c9', code: 'ST-09', title: 'Bird-Dog (Advanced)', titleTr: 'İleri Bird-Dog', category: 'Stability', difficulty: 7, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Bird-dog yaparken havada küçük daireler çizin.', biomechanics: 'Dynamic stabilization.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Multifidus'], rehabPhase: 'Kronik', movementPlane: 'Transverse', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430d0', code: 'ST-10', title: 'Swiss Ball Balance', titleTr: 'Swiss Ball Denge', category: 'Stability', difficulty: 5, sets: 3, reps: 30, restPeriod: 30, visualStyle: '4K-Render', description: 'Swiss ball üzerinde dik oturun.', biomechanics: 'Deep core postural control.', safetyFlags: ['Düşme Riski'], equipment: ['Swiss Ball'], primaryMuscles: ['Postural Muscles'], rehabPhase: 'Kronik', movementPlane: 'Combined', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 4 },

  // ==========================================
  // 5. NEUROLOGICAL (NÖROLOJİK) - 10 ITEMS
  // ==========================================
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d1', code: 'NE-01', title: 'Mirror Therapy', titleTr: 'Ayna Terapisi', category: 'Neurological', difficulty: 2, sets: 2, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Sağlam elinizi ayna önünde hareket ettirin.', biomechanics: 'Neuroplasticity stimulation.', safetyFlags: [], equipment: ['Ayna'], primaryMuscles: ['Brain'], rehabPhase: 'Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d2', code: 'NE-02', title: 'Weight Shifting', titleTr: 'Ağırlık Aktarma', category: 'Neurological', difficulty: 3, sets: 3, reps: 20, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Ağırlığınızı sağdan sola aktarın.', biomechanics: 'Balance and proprioception.', safetyFlags: ['Düşme Riski'], equipment: ['Yok'], primaryMuscles: ['Proprioceptors'], rehabPhase: 'Akut', movementPlane: 'Frontal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d3', code: 'NE-03', title: 'PNF Patterns (Arm)', titleTr: 'PNF Pattern (Kol)', category: 'Neurological', difficulty: 5, sets: 3, reps: 10, restPeriod: 45, visualStyle: '4K-Render', description: 'Kolunuzla çapraz bir kılıç çekme hareketi yapın.', biomechanics: 'Neuromuscular re-education.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Shoulder Complex'], rehabPhase: 'Sub-Akut', movementPlane: 'Oblique', tempo: '3-0-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d4', code: 'NE-04', title: 'Sit-to-Stand (Assisted)', titleTr: 'Otur-Kalk (Destekli)', category: 'Neurological', difficulty: 4, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Sandalyeden ellerinizi kullanarak kalkın.', biomechanics: 'Functional strength.', safetyFlags: [], equipment: ['Sandalye'], primaryMuscles: ['Quadriceps'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d5', code: 'NE-05', title: 'Finger-to-Nose', titleTr: 'Parmak-Burun Testi', category: 'Neurological', difficulty: 2, sets: 2, reps: 15, restPeriod: 20, visualStyle: 'Schematic', description: 'Parmağınızı burnunuza ve hedefe değdirin.', biomechanics: 'Coordination and cerebellar function.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Upper Limb'], rehabPhase: 'Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d6', code: 'NE-06', title: 'Ankle Dorsiflexion (Active)', titleTr: 'Aktif Ayak Çekme', category: 'Neurological', difficulty: 3, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'X-Ray', description: 'Ayağınızı yukarı doğru çekmeye çalışın.', biomechanics: 'Tibialis anterior activation.', safetyFlags: ['Foot Drop'], equipment: ['Yok'], primaryMuscles: ['Tibialis Anterior'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-2-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d7', code: 'NE-07', title: 'Marching in Place', titleTr: 'Olduğun Yerde Sayma', category: 'Neurological', difficulty: 4, sets: 3, reps: 30, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Dizleri karnınıza çekerek yerinizde sayın.', biomechanics: 'Dynamic balance.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Hip Flexors'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d8', code: 'NE-08', title: 'Toe Tapping', titleTr: 'Parmak Vurma', category: 'Neurological', difficulty: 2, sets: 3, reps: 20, restPeriod: 20, visualStyle: 'Schematic', description: 'Otuturken ayak parmaklarınızla yere vurun.', biomechanics: 'Distal coordination.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Ankle Flexors'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d9', code: 'NE-09', title: 'Box Reaching', titleTr: 'Uzanma Egzersizi', category: 'Neurological', difficulty: 5, sets: 3, reps: 10, restPeriod: 45, visualStyle: '4K-Render', description: 'Masadaki nesnelere farklı yönlerden uzanın.', biomechanics: 'Upper extremity functional range.', safetyFlags: [], equipment: ['Masa'], primaryMuscles: ['Shoulder', 'Core'], rehabPhase: 'Sub-Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430e0', code: 'NE-10', title: 'Crossover Steps', titleTr: 'Çapraz Adımlama', category: 'Neurological', difficulty: 6, sets: 2, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Ayaklarınızı birbirinin önünden geçirerek yürüyün.', biomechanics: 'Advanced balance and gait.', safetyFlags: ['Düşme Riski'], equipment: ['Yok'], primaryMuscles: ['Adductors', 'Glutes'], rehabPhase: 'Kronik', movementPlane: 'Frontal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 7 },

  // ==========================================
  // 6. CARDIOVASCULAR (KARDİYOVASKÜLER) - 10 ITEMS
  // ==========================================
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e1', code: 'CV-01', title: 'Pursed Lip Breathing', titleTr: 'Büzük Dudak Solunumu', category: 'Cardiovascular', difficulty: 1, sets: 2, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Burundan alıp dudakları büzerek yavaşça verin.', biomechanics: 'CO2 clearance.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Diaphragm'], rehabPhase: 'Akut', movementPlane: 'N/A', tempo: '4-8', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e2', code: 'CV-02', title: 'Arm Ergometer', titleTr: 'Kol Ergometresi', category: 'Cardiovascular', difficulty: 4, sets: 3, reps: 5, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Kollarınızla pedal çevirin (5 dk).', biomechanics: 'Upper body aerobic conditioning.', safetyFlags: ['Göğüs Ağrısı'], equipment: ['Ergometre'], primaryMuscles: ['Heart', 'Shoulders'], rehabPhase: 'Kronik', movementPlane: 'Combined', tempo: 'Consistent', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e3', code: 'CV-03', title: 'Step Ups', titleTr: 'Step Çıkma', category: 'Cardiovascular', difficulty: 5, sets: 3, reps: 15, restPeriod: 60, visualStyle: '4K-Render', description: 'Küçük bir basamağa çıkıp inin.', biomechanics: 'Cardiovascular load.', safetyFlags: ['Baş Dönmesi'], equipment: ['Basamak'], primaryMuscles: ['Quadriceps', 'Heart'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Steady', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e4', code: 'CV-04', title: 'Diaphragmatic Breathing', titleTr: 'Diyafram Solunumu', category: 'Cardiovascular', difficulty: 1, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Karnınızı şişirerek derin nefes alın.', biomechanics: 'Optimizing lung capacity.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Diaphragm'], rehabPhase: 'Akut', movementPlane: 'N/A', tempo: '3-0-6', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e5', code: 'CV-05', title: 'Walking (Interval)', titleTr: 'İnterval Yürüyüş', category: 'Cardiovascular', difficulty: 4, sets: 1, reps: 15, restPeriod: 0, visualStyle: 'Cinematic-Motion', description: 'Yavaş ve hızlı tempoda 15 dk yürüyün.', biomechanics: 'Aerobic endurance.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Heart', 'Legs'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Variable', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e6', code: 'CV-06', title: 'Seated Boxing', titleTr: 'Oturarak Boks', category: 'Cardiovascular', difficulty: 3, sets: 3, reps: 60, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Otururken hafif tempo yumruk atın.', biomechanics: 'High repetition conditioning.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Shoulders', 'Heart'], rehabPhase: 'Sub-Akut', movementPlane: 'Combined', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e7', code: 'CV-07', title: 'Knee-to-Chest Solunumu', titleTr: 'Solunumla Diz Çekme', category: 'Cardiovascular', difficulty: 3, sets: 3, reps: 12, restPeriod: 30, visualStyle: 'X-Ray', description: 'Nefes vererek dizinizi karnınıza çekin.', biomechanics: 'Integrated breathing/movement.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Diaphragm', 'Abs'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e8', code: 'CV-08', title: 'Wall Chest Expansion', titleTr: 'Göğüs Kafesi Açma', category: 'Cardiovascular', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Elleriniz duvarda göğüs kafesini gerin.', biomechanics: 'Improving rib cage mobility.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Intercostals'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: 'Static', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e9', code: 'CV-09', title: 'Shadow Boxing', titleTr: 'Gölge Boksu', category: 'Cardiovascular', difficulty: 6, sets: 3, reps: 120, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Ayakta hafif tempo boks yapın.', biomechanics: 'Aerobic power.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Full Body', 'Heart'], rehabPhase: 'Kronik', movementPlane: 'Combined', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430f0', code: 'CV-10', title: 'Lateral Rib Breathing', titleTr: 'Yanal Solunum', category: 'Cardiovascular', difficulty: 2, sets: 2, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Kaburgalarınızı yana doğru açarak nefes alın.', biomechanics: 'Lower lobe expansion.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Lower Diaphragm'], rehabPhase: 'Sub-Akut', movementPlane: 'N/A', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 2 },

  // ==========================================
  // 7. POST-OP (CERRAHİ SONRASI) - 10 ITEMS
  // ==========================================
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f1', code: 'PO-01', title: 'Quad Sets (Isometric)', titleTr: 'Quad Set (İzometrik)', category: 'Post-Op', difficulty: 1, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'X-Ray', description: 'Diz altındaki havluyu yere bastırın.', biomechanics: 'Isometric quad activation.', safetyFlags: [], equipment: ['Havlu'], primaryMuscles: ['Quadriceps'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '5s Hold', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f2', code: 'PO-02', title: 'Glute Squeezes', titleTr: 'Kalça Sıkıştırma', category: 'Post-Op', difficulty: 1, sets: 3, reps: 10, restPeriod: 20, visualStyle: 'Schematic', description: 'Yatarken kalçalarınızı 5 saniye sıkın.', biomechanics: 'Gluteal re-education.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Glutes'], rehabPhase: 'Akut', movementPlane: 'N/A', tempo: '5s Hold', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f3', code: 'PO-03', title: 'Active-Assisted ROM', titleTr: 'Yardımlı Eklem Hareket', category: 'Post-Op', difficulty: 2, sets: 3, reps: 15, restPeriod: 30, visualStyle: '4K-Render', description: 'Sağlam elinizle ameliyatlı kolu kaldırın.', biomechanics: 'Gentle joint mobilization.', safetyFlags: ['Cerrahi Dikiş Gerginliği'], equipment: ['Yok'], primaryMuscles: ['Shoulder/Knee'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f4', code: 'PO-04', title: 'Ankle Pumps (Circulation)', titleTr: 'Dolaşım Pompası', category: 'Post-Op', difficulty: 1, sets: 5, reps: 20, restPeriod: 30, visualStyle: 'Schematic', description: 'Ayak bileğinizi sürekli oynatın.', biomechanics: 'Prevention of DVT.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Calf Pump'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f5', code: 'PO-05', title: 'Wall Slides (Heel)', titleTr: 'Topuk Kaydırma (Duvar)', category: 'Post-Op', difficulty: 3, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Ayağınızı duvarda yavaşça kaydırın.', biomechanics: 'Gravity-assisted flexion.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Knee Flexors'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f6', code: 'PO-06', title: 'Patellar Mobilization', titleTr: 'Diz Kapağı Mobilizasyonu', category: 'Post-Op', difficulty: 2, sets: 2, reps: 10, restPeriod: 30, visualStyle: 'X-Ray', description: 'Diz kapağınızı elinizle hafifçe oynatın.', biomechanics: 'Improving patellar tracking.', safetyFlags: ['Enfeksiyon'], equipment: ['Yok'], primaryMuscles: ['Patella'], rehabPhase: 'Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f7', code: 'PO-07', title: 'Short Arc Quads', titleTr: 'Kısa Ark Quad', category: 'Post-Op', difficulty: 3, sets: 3, reps: 15, restPeriod: 45, visualStyle: '4K-Render', description: 'Diz altındaki rulo ile dizinizi düzeltin.', biomechanics: 'Terminal knee extension.', safetyFlags: [], equipment: ['Rulo'], primaryMuscles: ['Quads'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '2-2-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f8', code: 'PO-08', title: 'Isometric Hip Abduction', titleTr: 'İzometrik Kalça Açma', category: 'Post-Op', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Dizlerinizi dışa doğru bandın direncine itin.', biomechanics: 'Early gluteal strengthening.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Gluteus Medius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: '5s Hold', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f9', code: 'PO-09', title: 'Seated Knee Extension', titleTr: 'Oturarak Diz Düzeltme', category: 'Post-Op', difficulty: 3, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Otururken ayağınızı yukarı kaldırıp bekletin.', biomechanics: 'Concentric quad strength.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Quadriceps'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-2-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd43100', code: 'PO-10', title: 'Standing Hip Extension', titleTr: 'Ayakta Kalça Ekstansiyon', category: 'Post-Op', difficulty: 4, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Ayaktayken bacağınızı arkaya doğru açın.', biomechanics: 'Posterior chain re-education.', safetyFlags: ['Bel Boşluğu'], equipment: ['Sandalye (Destek)'], primaryMuscles: ['Gluteus Maximus'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 }
];
