
import { Exercise } from './types.ts';

/**
 * PHYSIOCORE MASTER CLINICAL LIBRARY v12.0 (ULTRA-PRO EDITION)
 * 7 Categories x 10 Exercises = 70 Professional Gold-Standard Records.
 * Includes advanced biomechanics, modern rehabilitation protocols, and EBM citations.
 */
export const SEED_EXERCISES: Exercise[] = [
  // ==========================================
  // 1. SPINE (OMURGA) - 10 ITEMS
  // ==========================================
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d471', code: 'SP-01', title: 'McKenzie Prone Press-up', titleTr: 'McKenzie Yüzüstü Doğrulma',
    category: 'Spine', difficulty: 3, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion',
    description: 'Yüzüstü yatın, kollarınızla gövdenizi kalçayı yerden ayırmadan yukarı itin. Bel bölgesinde "santralizasyon" (ağrının merkeze toplanması) hedeflenir.',
    biomechanics: 'L4-L5/L5-S1 segmentinde anterior disk migrasyonu ve mekanik dekompresyon sağlar.',
    safetyFlags: ['Spondylolisthesis', 'Akut Faset Sendromu'], equipment: ['Mat'], primaryMuscles: ['Erector Spinae'],
    rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-2-2', secondaryMuscles: ['Triceps'], isMotion: true, targetRpe: 4
  },
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d472', code: 'SP-02', title: 'Bird-Dog Precision', titleTr: 'Bird-Dog (Stabilizasyon)',
    category: 'Spine', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'X-Ray',
    description: 'Dört ayak üzerinde nötr omurga pozisyonunu koruyarak çapraz kol ve bacağı uzatın. Pelvisin rotasyonunu engelleyin (Sırtınızda su dolu bardak varmış gibi).',
    biomechanics: 'Multifidus izometrik aktivasyonu ve anti-rotasyonel core kontrolü.',
    safetyFlags: ['Denge Kaybı'], equipment: ['Mat'], primaryMuscles: ['Multifidus', 'Transversus Abd.'],
    rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '3-3-3', secondaryMuscles: ['Gluteus Max', 'Deltoid'], isMotion: true, targetRpe: 6
  },
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d473', code: 'SP-03', title: 'Open Book Stretch', titleTr: 'Open Book (Torakal Mobilite)',
    category: 'Spine', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic',
    description: 'Yan yatış pozisyonunda, üstteki kolu geriye doğru açarak göğüs kafesini ve sırtı esnetin. Kalçalar sabit kalmalıdır.',
    biomechanics: 'Torakal omurga rotasyonu ve Pektoral fasya gevşetme.',
    safetyFlags: ['Omuz İnstabilitesi'], equipment: ['Mat'], primaryMuscles: ['Thoracic Paraspinals'],
    rehabPhase: 'Akut', movementPlane: 'Transverse', tempo: 'Slow', secondaryMuscles: ['Pectoralis Major'], isMotion: true, targetRpe: 3
  },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d474', code: 'SP-04', title: 'Chin Tucks (Deep Flexor)', titleTr: 'Chin Tuck (Derin Fleksör)', category: 'Spine', difficulty: 2, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'X-Ray', description: 'Başınızı geriye doğru çekerek "gıdı çıkarma" hareketi yapın. Yüzeyel kasları gevşetip derin boyun kaslarını çalıştırır.', biomechanics: 'Deep Neck Flexors (Longus Colli) aktivasyonu ve servikal lordoz düzeltme.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Longus Colli'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '3-5-3', secondaryMuscles: ['Suboccipitals'], isMotion: true, targetRpe: 3 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d475', code: 'SP-05', title: 'Cat-Camel Segmentation', titleTr: 'Kedi-Deve (Segmental)', category: 'Spine', difficulty: 3, sets: 3, reps: 10, restPeriod: 30, visualStyle: '4K-Render', description: 'Omurgayı kuyruk sokumundan başlayarak tek tek (segmental) hareket ettirerek bükün ve düzleştirin.', biomechanics: 'Vertebral segmentasyon ve nöromusküler kontrol.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Multifidus', 'Erector Spinae'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '4-0-4', secondaryMuscles: ['Abs'], isMotion: true, targetRpe: 2 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d476', code: 'SP-06', title: 'Sciatic Nerve Flossing', titleTr: 'Siyatik Sinir Kaydırma', category: 'Spine', difficulty: 4, sets: 2, reps: 15, restPeriod: 45, visualStyle: 'Nerve-Highlight', description: 'Sırtüstü yatarken bacağınızı kaldırın, ayak bileğini ve boynu senkronize hareket ettirerek siniri "kaydırın". Gerilim değil, hareket esastır.', biomechanics: 'Nörodinamik mobilizasyon (Neurodynamics).', safetyFlags: ['Akut Radikülopati'], equipment: ['Mat'], primaryMuscles: ['Neural Tissue'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Fluid', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d477', code: 'SP-07', title: 'Wall Angels', titleTr: 'Duvar Meleği', category: 'Spine', difficulty: 5, sets: 3, reps: 12, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Sırt, baş ve kalça duvara temas ederken kollarınızı "W" harfinden "I" harfine kaydırın.', biomechanics: 'Torakal ekstansiyon ve skapular retraksiyon.', safetyFlags: ['Omuz İmpingement'], equipment: ['Duvar'], primaryMuscles: ['Lower Trapezius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: '3-2-3', secondaryMuscles: ['Rhomboids'], isMotion: true, targetRpe: 6 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d478', code: 'SP-08', title: 'Jefferson Curl (Light)', titleTr: 'Jefferson Curl (Hafif)', category: 'Spine', difficulty: 7, sets: 3, reps: 8, restPeriod: 60, visualStyle: '4K-Render', description: 'Ayakta, çok hafif bir ağırlıkla omurgayı boyundan başlayarak yavaşça aşağı yuvarlayın ve tekrar yukarı toplayın.', biomechanics: 'Posterior zincir fasya esnekliği ve segmental güçlenme.', safetyFlags: ['Akut Disk Hernisi', 'Osteoporoz'], equipment: ['Hafif Dumbbell'], primaryMuscles: ['Erector Spinae'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '5-2-5', secondaryMuscles: ['Hamstrings'], isMotion: true, targetRpe: 6 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479', code: 'SP-09', title: 'Pallof Press (Kneeling)', titleTr: 'Dizüstü Pallof Press', category: 'Spine', difficulty: 6, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Yarım dizüstü pozisyonda, yan taraftan gelen dirence karşı ellerinizi göğüsten ileri itin.', biomechanics: 'Anti-rotasyonel stabilite.', safetyFlags: [], equipment: ['Bant/Kablo'], primaryMuscles: ['Obliques'], rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '2-3-2', secondaryMuscles: ['Glutes'], isMotion: true, targetRpe: 7 },
  { id: 'f47ac10b-58cc-4372-a567-0e02b2c3d480', code: 'SP-10', title: 'Child\'s Pose to Cobra', titleTr: 'Çocuk Pozu - Kobra Akışı', category: 'Spine', difficulty: 3, sets: 3, reps: 8, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Topuklara oturma pozisyonundan (fleksiyon) yavaşça öne kayarak ekstansiyon pozisyonuna geçin.', biomechanics: 'Full range spinal mobility.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Spinals'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Flow', secondaryMuscles: ['Shoulders'], isMotion: true, targetRpe: 3 },

  // ==========================================
  // 2. LOWER LIMB (ALT EKSTREMİTE) - 10 ITEMS
  // ==========================================
  { id: '6ba7b810-9dad-11d1-80b4-00c04fd430c8', code: 'LL-01', title: 'Nordic Hamstring Curl', titleTr: 'Nordic Hamstring Curl', category: 'Lower Limb', difficulty: 9, sets: 3, reps: 6, restPeriod: 90, visualStyle: 'Cinematic-Motion', description: 'Dizler sabitken gövdeyi yavaşça öne bırakın. Hamstring yaralanmalarını önlemede altın standart.', biomechanics: 'Supramaximal eccentric hamstring loading.', safetyFlags: ['Akut Hamstring Yırtığı'], equipment: ['Sabit Destek'], primaryMuscles: ['Hamstrings'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Slow Eccentric', secondaryMuscles: ['Glutes'], isMotion: true, targetRpe: 9 },
  { id: '6ba7b810-9dad-11d1-80b4-00c04fd430c9', code: 'LL-02', title: 'Single Leg RDL', titleTr: 'Tek Ayak RDL', category: 'Lower Limb', difficulty: 7, sets: 3, reps: 10, restPeriod: 60, visualStyle: '4K-Render', description: 'Tek ayak üzerinde dururken gövdeyi öne, bacağı arkaya uzatın. "T" harfi oluşturun.', biomechanics: 'Dinamik kalça stabilitesi ve posterior zincir kontrolü.', safetyFlags: ['Denge Sorunu'], equipment: ['Kettlebell (Opsiyonel)'], primaryMuscles: ['Gluteus Max', 'Hamstrings'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '3-1-2', secondaryMuscles: ['Foot Intrinsic'], isMotion: true, targetRpe: 7 },
  { id: '6ba7b810-9dad-11d1-80b4-00c04fd430d0', code: 'LL-03', title: 'Goblet Squat', titleTr: 'Goblet Squat', category: 'Lower Limb', difficulty: 5, sets: 4, reps: 12, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Ağırlığı göğüs hizasında tutarak tam çökme yapın. Gövde dikliğini koruyun.', biomechanics: 'Deep knee flexion ve torakal ekstansiyon.', safetyFlags: ['Menisküs Yırtığı'], equipment: ['Dumbbell'], primaryMuscles: ['Quadriceps', 'Glutes'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '3-1-1', secondaryMuscles: ['Core'], isMotion: true, targetRpe: 7 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d1', code: 'LL-04', title: 'Monster Walk', titleTr: 'Monster Walk (Yanal Yürüyüş)', category: 'Lower Limb', difficulty: 4, sets: 3, reps: 20, restPeriod: 45, visualStyle: 'X-Ray', description: 'Ayak bileklerinde bant varken dizleri büküp yan yan yürüyün.', biomechanics: 'Gluteus Medius izalosyonu.', safetyFlags: [], equipment: ['Loop Band'], primaryMuscles: ['Gluteus Medius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: 'Controlled', secondaryMuscles: ['TFL'], isMotion: true, targetRpe: 6 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d2', code: 'LL-05', title: 'Tibialis Raises', titleTr: 'Tibialis Kaldırma', category: 'Lower Limb', difficulty: 3, sets: 3, reps: 20, restPeriod: 30, visualStyle: 'Schematic', description: 'Sırtınızı duvara yaslayıp ayak parmaklarınızı kendinize çekin.', biomechanics: 'Shin splint önleme ve ayak bileği dorsifleksiyon gücü.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Tibialis Anterior'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '1-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d3', code: 'LL-06', title: 'Bulgarian Split Squat', titleTr: 'Bulgar Squat', category: 'Lower Limb', difficulty: 8, sets: 3, reps: 10, restPeriod: 90, visualStyle: 'Cinematic-Motion', description: 'Arka ayağı yükseltiye koyarak tek bacakla çökün.', biomechanics: 'Unilateral bacak kuvveti ve kalça fleksör esnekliği.', safetyFlags: ['Diz Ağrısı'], equipment: ['Bench/Sandalye'], primaryMuscles: ['Quadriceps', 'Glutes'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: '3-1-1', secondaryMuscles: ['Adductors'], isMotion: true, targetRpe: 8 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d4', code: 'LL-07', title: 'Copenhagen Plank', titleTr: 'Copenhagen Plank', category: 'Lower Limb', difficulty: 8, sets: 3, reps: 30, restPeriod: 60, visualStyle: 'Muscle-Map', description: 'Yan plank pozisyonunda, üstteki bacak bir sıranın üzerindeyken alttaki bacağı ona yaklaştırın.', biomechanics: 'High-intensity Adductor strengthening.', safetyFlags: ['Kasık Ağrısı'], equipment: ['Bench'], primaryMuscles: ['Adductors'], rehabPhase: 'Performans', movementPlane: 'Frontal', tempo: 'Isometric', secondaryMuscles: ['Obliques'], isMotion: true, targetRpe: 9 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d5', code: 'LL-08', title: 'Terminal Knee Extension (TKE)', titleTr: 'TKE (Diz Kilitleme)', category: 'Lower Limb', difficulty: 2, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'X-Ray', description: 'Diz arkasındaki bandı gererek dizi tam düzeltin ve VMO kasını sıkın.', biomechanics: 'Vastus Medialis (VMO) son derece aktivasyonu.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Vastus Medialis'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-3-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d6', code: 'LL-09', title: 'Step Downs', titleTr: 'Step Down (Eksentrik)', category: 'Lower Limb', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Basamaktan tek ayakla yavaşça inin, dizin içe dönmesini engelleyin.', biomechanics: 'Patellar tendon yüklenmesi ve eksentrik quad kontrolü.', safetyFlags: ['Patellar Tendinit'], equipment: ['Basamak'], primaryMuscles: ['Quadriceps'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '4-0-1', secondaryMuscles: ['Glute Med'], isMotion: true, targetRpe: 6 },
  { id: '6ba7b811-9dad-11d1-80b4-00c04fd430d7', code: 'LL-10', title: 'Glute Bridge March', titleTr: 'Köprüde Yürüyüş', category: 'Lower Limb', difficulty: 4, sets: 3, reps: 20, restPeriod: 45, visualStyle: '4K-Render', description: 'Köprü pozisyonunu bozmadan sırayla dizleri karnınıza çekin.', biomechanics: 'Pelvik stabilite ve hamstring/glute dayanıklılığı.', safetyFlags: ['Bel Ağrısı'], equipment: ['Mat'], primaryMuscles: ['Glutes', 'Hamstrings'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Marching', secondaryMuscles: ['Core'], isMotion: true, targetRpe: 5 },

  // ==========================================
  // 3. UPPER LIMB (ÜST EKSTREMİTE) - 10 ITEMS
  // ==========================================
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a1', code: 'UL-01', title: 'Y-T-W-L Series', titleTr: 'Y-T-W-L Serisi', category: 'Upper Limb', difficulty: 4, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Muscle-Map', description: 'Yüzüstü veya eğilerek kolları sırayla Y, T, W ve L harflerine benzeterek kaldırın.', biomechanics: 'Lower Trapezius ve Rotator Cuff aktivasyonu.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Trapezius', 'Rhomboids'], rehabPhase: 'Sub-Akut', movementPlane: 'Multi-Planar', tempo: '2-2-2', secondaryMuscles: ['Rear Deltoid'], isMotion: true, targetRpe: 5 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a2', code: 'UL-02', title: 'Serratus Wall Slides', titleTr: 'Serratus Duvar Kaydırma', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 12, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Ön kollara bant takıp duvarda yukarı kaydırın, kürek kemiklerini öne itin.', biomechanics: 'Scapular upward rotation ve protraksiyon.', safetyFlags: ['Winged Scapula'], equipment: ['Mini Band', 'Foam Roller'], primaryMuscles: ['Serratus Anterior'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a3', code: 'UL-03', title: 'Median Nerve Glide', titleTr: 'Median Sinir Kaydırma', category: 'Upper Limb', difficulty: 2, sets: 2, reps: 10, restPeriod: 30, visualStyle: 'Nerve-Highlight', description: 'Kolu yana açıp el bileğini ve boynu ters yönlere hareket ettirerek siniri kaydırın.', biomechanics: 'Karpal tünel ve servikal kök rahatlatma.', safetyFlags: ['Uyuşma Artışı'], equipment: ['Yok'], primaryMuscles: ['Nerve Bed'], rehabPhase: 'Akut', movementPlane: 'Frontal', tempo: 'Flow', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a4', code: 'UL-04', title: 'Face Pulls', titleTr: 'Face Pull', category: 'Upper Limb', difficulty: 5, sets: 3, reps: 15, restPeriod: 45, visualStyle: '4K-Render', description: 'Kabloyu veya bandı yüzünüze doğru çekerken omuzları dışa rotasyona zorlayın.', biomechanics: 'External rotation ve posterior deltoid kuvveti.', safetyFlags: [], equipment: ['Bant/Kablo'], primaryMuscles: ['Rotator Cuff', 'Rear Delt'], rehabPhase: 'Kronik', movementPlane: 'Transverse', tempo: '2-1-2', secondaryMuscles: ['Rhomboids'], isMotion: true, targetRpe: 6 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a5', code: 'UL-05', title: 'Isometric Shoulder Abd', titleTr: 'İzometrik Omuz Abdüksiyon', category: 'Upper Limb', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Kolu yan taraftan duvara dayayıp itin, hareket etmeden kasın.', biomechanics: 'Deltoid ve Supraspinatus statik aktivasyonu.', safetyFlags: ['Akut Yırtık'], equipment: ['Duvar'], primaryMuscles: ['Deltoid'], rehabPhase: 'Akut', movementPlane: 'Frontal', tempo: '5s Hold', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a6', code: 'UL-06', title: 'Farmers Carry', titleTr: 'Çiftçi Yürüyüşü', category: 'Upper Limb', difficulty: 6, sets: 3, reps: 60, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Ellerde ağır dambıllarla dik duruşu bozmadan yürüyün.', biomechanics: 'Grip strength ve dinamik omuz stabilitesi.', safetyFlags: [], equipment: ['Dumbbell/Kettlebell'], primaryMuscles: ['Forearm', 'Traps'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Walk', secondaryMuscles: ['Core'], isMotion: true, targetRpe: 7 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a7', code: 'UL-07', title: 'Doorway Pec Stretch', titleTr: 'Kapı Eşiği Germe', category: 'Upper Limb', difficulty: 1, sets: 2, reps: 30, restPeriod: 20, visualStyle: 'X-Ray', description: 'Kolları kapı eşiğine koyup gövdeyi öne bırakın.', biomechanics: 'Pectoralis Major/Minor esnetme.', safetyFlags: ['Anterior Omuz Ağrısı'], equipment: ['Kapı'], primaryMuscles: ['Pectorals'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Static', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a8', code: 'UL-08', title: 'Eccentric Wrist Ext', titleTr: 'Eksentrik Bilek (Tenisçi)', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'Close-Up', description: 'Ağırlığı diğer elle kaldırın, hasta elle yavaşça (4 saniyede) indirin.', biomechanics: 'Lateral epikondilit için tendon yüklemesi.', safetyFlags: [], equipment: ['Dumbbell'], primaryMuscles: ['Wrist Extensors'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Help-up, 4s down', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430a9', code: 'UL-09', title: 'PNF D2 Flexion', titleTr: 'PNF D2 (Kılıç Çekme)', category: 'Upper Limb', difficulty: 5, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Elinizi karşı cebinizden çapraz yukarı dışarı doğru açın.', biomechanics: 'Fonksiyonel omuz paternleri.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Deltoid', 'Rotator Cuff'], rehabPhase: 'Kronik', movementPlane: 'Diagonal', tempo: '2-1-2', secondaryMuscles: ['Scapular Stab'], isMotion: true, targetRpe: 6 },
  { id: '7ba7b811-9dad-11d1-80b4-00c04fd430b0', code: 'UL-10', title: 'Scapular Push-ups', titleTr: 'Skapular Şınav', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'Schematic', description: 'Dirsekleri bükmeden sadece kürek kemiklerini hareket ettirerek gövdeyi düşürüp kaldırın.', biomechanics: 'Serratus Anterior izolasyonu.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Serratus Anterior'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },

  // ==========================================
  // 4. STABILITY (STABİLİZASYON) - 10 ITEMS
  // ==========================================
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c1', code: 'ST-01', title: 'Stir the Pot', titleTr: 'Stir the Pot (Swiss Ball)', category: 'Stability', difficulty: 8, sets: 3, reps: 10, restPeriod: 60, visualStyle: '4K-Render', description: 'Plank pozisyonunda dirsekler toptayken topla daireler çizin. Bel sabit kalmalı.', biomechanics: 'Anti-extension ve dinamik core stabilitesi (McGill Big 3 extension).', safetyFlags: ['Bel Ağrısı'], equipment: ['Swiss Ball'], primaryMuscles: ['Core'], rehabPhase: 'Performans', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: ['Shoulders'], isMotion: true, targetRpe: 9 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c2', code: 'ST-02', title: 'Dead Bug (Wall Push)', titleTr: 'Dead Bug (Duvar İtme)', category: 'Stability', difficulty: 6, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'X-Ray', description: 'Sırtüstü ellerle duvarı iterken (core aktivasyonu için) bacakları sırayla uzatın.', biomechanics: 'Anterior core tension ve pelvik tilt kontrolü.', safetyFlags: [], equipment: ['Duvar', 'Mat'], primaryMuscles: ['Transversus Abd'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-0-3', secondaryMuscles: ['Hip Flexors'], isMotion: true, targetRpe: 7 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c3', code: 'ST-03', title: 'Suitcase Carry', titleTr: 'Bavul Taşıma', category: 'Stability', difficulty: 5, sets: 3, reps: 60, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Tek elde ağır bir yükle gövdenin yana eğilmesine izin vermeden yürüyün.', biomechanics: 'Anti-lateral flexion.', safetyFlags: [], equipment: ['Kettlebell'], primaryMuscles: ['Obliques', 'Quadratus Lumborum'], rehabPhase: 'Kronik', movementPlane: 'Frontal', tempo: 'Walk', secondaryMuscles: ['Grip'], isMotion: true, targetRpe: 7 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c4', code: 'ST-04', title: 'Pallof Press', titleTr: 'Pallof Press', category: 'Stability', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: '4K-Render', description: 'Ayakta yan taraftan gelen dirence karşı elleri ileri itin ve bekleyin.', biomechanics: 'Anti-rotation.', safetyFlags: [], equipment: ['Bant/Kablo'], primaryMuscles: ['Obliques'], rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '2-3-2', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c5', code: 'ST-05', title: 'Side Plank Rotations', titleTr: 'Yan Plank Rotasyon', category: 'Stability', difficulty: 7, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Yan plank pozisyonunda üstteki kolla gövdenin altına uzanın ve açılın.', biomechanics: 'Lateral stabilite + rotasyonel kontrol.', safetyFlags: ['Omuz Ağrısı'], equipment: ['Mat'], primaryMuscles: ['Obliques', 'Shoulder'], rehabPhase: 'Kronik', movementPlane: 'Multi-Planar', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c6', code: 'ST-06', title: 'Single Leg RDL (Balance)', titleTr: 'Tek Ayak RDL (Denge)', category: 'Stability', difficulty: 6, sets: 3, reps: 8, restPeriod: 45, visualStyle: 'X-Ray', description: 'Tek ayak üzerinde öne eğilin, arka bacak ve gövde yere paralel olsun.', biomechanics: 'Posterior chain ve ayak bileği propriyosepsiyonu.', safetyFlags: ['Denge Kaybı'], equipment: ['Yok'], primaryMuscles: ['Hamstrings', 'Glutes'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '3-1-1', secondaryMuscles: ['Foot Intrinsic'], isMotion: true, targetRpe: 6 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c7', code: 'ST-07', title: 'Bear Crawl', titleTr: 'Ayı Yürüyüşü', category: 'Stability', difficulty: 7, sets: 3, reps: 20, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Dizler yerden 5cm yukarıda, sırt düz şekilde zıt kol ve bacakla ilerleyin.', biomechanics: 'Dinamik core ve omuz stabilitesi.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Core', 'Quads'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Controlled', secondaryMuscles: ['Shoulders'], isMotion: true, targetRpe: 8 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c8', code: 'ST-08', title: 'Bosu Ball Squat', titleTr: 'Bosu Topu Squat', category: 'Stability', difficulty: 6, sets: 3, reps: 15, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Bosu topunun dengesiz yüzeyinde squat yapın.', biomechanics: 'Nöromusküler adaptasyon.', safetyFlags: ['Düşme Riski'], equipment: ['Bosu Ball'], primaryMuscles: ['Legs', 'Core'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: ['Ankle Stab'], isMotion: true, targetRpe: 7 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430c9', code: 'ST-09', title: 'Turkish Get Up (Half)', titleTr: 'Yarım TGU', category: 'Stability', difficulty: 8, sets: 3, reps: 5, restPeriod: 90, visualStyle: '4K-Render', description: 'Sırtüstü elinde ağırlıkla başlayıp dirsek ve el üzerine doğrulma.', biomechanics: 'Tüm vücut entegrasyonu.', safetyFlags: ['Omuz İmpingement'], equipment: ['Kettlebell'], primaryMuscles: ['Full Body'], rehabPhase: 'Performans', movementPlane: 'Multi-Planar', tempo: 'Flow', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: '8ba7b811-9dad-11d1-80b4-00c04fd430d0', code: 'ST-10', title: 'RKC Plank', titleTr: 'RKC Plank (High Tension)', category: 'Stability', difficulty: 9, sets: 4, reps: 15, restPeriod: 60, visualStyle: 'Muscle-Map', description: 'Normal plank pozisyonunda dirsekleri ve ayakları birbirine çekerek maksimum gerilim yaratın.', biomechanics: 'Maximal core recruitment (Irradiation).', safetyFlags: ['Hipertansiyon'], equipment: ['Mat'], primaryMuscles: ['Rectus Abd'], rehabPhase: 'Performans', movementPlane: 'Isometric', tempo: '10s Max', secondaryMuscles: ['Glutes', 'Lats'], isMotion: true, targetRpe: 10 },

  // ==========================================
  // 5. NEUROLOGICAL (NÖROLOJİK) - 10 ITEMS
  // ==========================================
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d1', code: 'NE-01', title: 'Mirror Therapy (Hand)', titleTr: 'Ayna Terapisi', category: 'Neurological', difficulty: 2, sets: 3, reps: 5, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Ayna kutusunda sağlam eli hareket ettirerek felçli tarafı hareket ediyormuş gibi izleyin.', biomechanics: 'Kortikal yeniden haritalama (Neuroplasticity).', safetyFlags: [], equipment: ['Ayna'], primaryMuscles: ['Brain'], rehabPhase: 'Akut', movementPlane: 'Visual', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d2', code: 'NE-02', title: 'Proprioceptive Clock', titleTr: 'Saat Yönü Uzanma', category: 'Neurological', difficulty: 4, sets: 2, reps: 5, restPeriod: 45, visualStyle: 'Floor-Grid', description: 'Tek ayak üzerinde dururken diğer ayakla hayali bir saatin 12, 3, 6, 9 yönlerine dokunun.', biomechanics: 'Dinamik denge ve propriyosepsiyon.', safetyFlags: ['Düşme Riski'], equipment: ['Yok'], primaryMuscles: ['Legs', 'Vestibular'], rehabPhase: 'Sub-Akut', movementPlane: 'Combined', tempo: 'Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d3', code: 'NE-03', title: 'Dual Task Walking', titleTr: 'Çift Görevli Yürüyüş', category: 'Neurological', difficulty: 6, sets: 1, reps: 60, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Yürürken geriye doğru 100\'den 7\'şer 7\'şer sayın veya elinizde su dolu bardak taşıyın.', biomechanics: 'Kognitif-Motor interferans eğitimi.', safetyFlags: ['Düşme Riski'], equipment: ['Engel/Bardak'], primaryMuscles: ['Brain', 'Gait'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Walk', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d4', code: 'NE-04', title: 'Sit-to-Stand (No Hands)', titleTr: 'Desteksiz Otur-Kalk', category: 'Neurological', difficulty: 4, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'X-Ray', description: 'Kolları göğüste çaprazlayarak sandalyeden kalkıp oturun.', biomechanics: 'Alt ekstremite fonksiyonel kuvveti.', safetyFlags: ['Denge'], equipment: ['Sandalye'], primaryMuscles: ['Quadriceps', 'Glutes'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Power up, Slow down', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d5', code: 'NE-05', title: 'Tandem Stance (Eyes Closed)', titleTr: 'Tandem Duruş (Göz Kapalı)', category: 'Neurological', difficulty: 5, sets: 3, reps: 30, restPeriod: 30, visualStyle: 'Schematic', description: 'Bir ayak diğerinin tam önünde (topuk-parmak teması) gözler kapalı bekleyin.', biomechanics: 'Vestibüler ve somatosensoryal entegrasyon.', safetyFlags: ['Düşme Riski'], equipment: ['Köşe Duvar'], primaryMuscles: ['Postural'], rehabPhase: 'Kronik', movementPlane: 'Static', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d6', code: 'NE-06', title: 'PNF D1 Pattern (Upper)', titleTr: 'PNF D1 (Emniyet Kemeri)', category: 'Neurological', difficulty: 4, sets: 3, reps: 10, restPeriod: 30, visualStyle: '4K-Render', description: 'Elinizi emniyet kemerini takar gibi yukarı-dıştan aşağı-içe hareket ettirin.', biomechanics: 'Diyagonal fonksiyonel paternler.', safetyFlags: [], equipment: ['Bant (Opsiyonel)'], primaryMuscles: ['Shoulder'], rehabPhase: 'Sub-Akut', movementPlane: 'Diagonal', tempo: 'Fluid', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d7', code: 'NE-07', title: 'Frenkel Exercises (Lying)', titleTr: 'Frenkel Egzersizleri', category: 'Neurological', difficulty: 3, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Schematic', description: 'Sırtüstü yatarken topuğunuzu diğer bacağın kaval kemiği üzerinde düzgünce kaydırın.', biomechanics: 'Ataksi ve koordinasyon bozukluğu rehabilitasyonu.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Lower Limb'], rehabPhase: 'Akut', movementPlane: 'Combined', tempo: 'Slow/Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d8', code: 'NE-08', title: 'Weight Shifting (AP/ML)', titleTr: 'Ağırlık Aktarma', category: 'Neurological', difficulty: 3, sets: 3, reps: 20, restPeriod: 30, visualStyle: 'Center-of-Pressure', description: 'Ayakta ayakları oynatmadan ağırlığı öne-arkaya ve sağa-sola verin (Sway control).', biomechanics: 'Denge stratejileri (Ankle/Hip strategy).', safetyFlags: ['Düşme Riski'], equipment: ['Yok'], primaryMuscles: ['Core', 'Ankle'], rehabPhase: 'Sub-Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430d9', code: 'NE-09', title: 'Scapular PNF', titleTr: 'Skapular PNF', category: 'Neurological', difficulty: 3, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Muscle-Map', description: 'Yan yatışta terapist direncine karşı (veya aktif) kürek kemiğini öne-yukarı ve arkaya-aşağı hareket ettirin.', biomechanics: 'Proksimal stabilite.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Scapular Stabilizers'], rehabPhase: 'Akut', movementPlane: 'Diagonal', tempo: 'Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: '9ba7b811-9dad-11d1-80b4-00c04fd430e0', code: 'NE-10', title: 'Balloon Taps', titleTr: 'Balon Sektirme', category: 'Neurological', difficulty: 4, sets: 2, reps: 60, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Ayakta bir balonu yere düşürmeden havada tutmaya çalışın.', biomechanics: 'Reaktif denge ve el-göz koordinasyonu.', safetyFlags: ['Düşme Riski'], equipment: ['Balon'], primaryMuscles: ['Full Body'], rehabPhase: 'Sub-Akut', movementPlane: 'Random', tempo: 'Reactive', secondaryMuscles: [], isMotion: true, targetRpe: 5 },

  // ==========================================
  // 6. CARDIOVASCULAR (KARDİYOVASKÜLER) - 10 ITEMS
  // ==========================================
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e1', code: 'CV-01', title: 'Recumbent Bike Intervals', titleTr: 'Yatay Bisiklet İnterval', category: 'Cardiovascular', difficulty: 4, sets: 1, reps: 15, restPeriod: 0, visualStyle: 'Cinematic-Motion', description: 'Yatay bisiklette 1 dk hızlı, 2 dk yavaş tempo sürüş.', biomechanics: 'Düşük etkili aerobik yüklenme.', safetyFlags: [], equipment: ['Yatay Bisiklet'], primaryMuscles: ['Legs', 'Heart'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Interval', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e2', code: 'CV-02', title: 'Arm Ergometer (UBE)', titleTr: 'Kol Ergometresi', category: 'Cardiovascular', difficulty: 3, sets: 1, reps: 10, restPeriod: 0, visualStyle: 'Cinematic-Motion', description: 'El bisikletini ileri veya geri yönde çevirin.', biomechanics: 'Üst ekstremite dayanıklılığı.', safetyFlags: ['Omuz Ağrısı'], equipment: ['UBE'], primaryMuscles: ['Shoulder', 'Heart'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Steady', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e3', code: 'CV-03', title: 'Seated Marching (Rapid)', titleTr: 'Oturarak Hızlı Adım', category: 'Cardiovascular', difficulty: 2, sets: 3, reps: 60, restPeriod: 30, visualStyle: 'X-Ray', description: 'Sandalyede otururken hızlı tempoda dizleri çekip indirin.', biomechanics: 'Kalça fleksör dayanıklılığı ve kalp hızı artışı.', safetyFlags: [], equipment: ['Sandalye'], primaryMuscles: ['Hip Flexors'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e4', code: 'CV-04', title: 'Box Step Ups', titleTr: 'Step Kutusuna Çıkış', category: 'Cardiovascular', difficulty: 5, sets: 3, reps: 20, restPeriod: 45, visualStyle: '4K-Render', description: 'Ritmik bir şekilde step tahtasına çıkıp inin.', biomechanics: 'Konsantrik/Eksentrik bacak kuvveti ve aerobik.', safetyFlags: ['Diz Ağrısı'], equipment: ['Step Tahtası'], primaryMuscles: ['Quads', 'Glutes'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Rhythmic', secondaryMuscles: ['Calves'], isMotion: true, targetRpe: 7 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e5', code: 'CV-05', title: 'Battle Ropes (Seated)', titleTr: 'Halat Sallama (Oturarak)', category: 'Cardiovascular', difficulty: 6, sets: 3, reps: 30, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Otururken halatları dalgalandırın.', biomechanics: 'Üst gövde anaerobik güç.', safetyFlags: ['Omuz İmpingement'], equipment: ['Battle Rope'], primaryMuscles: ['Shoulders', 'Core'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Max Effort', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e6', code: 'CV-06', title: 'Sit-to-Stand Intervals', titleTr: 'Otur-Kalk İnterval', category: 'Cardiovascular', difficulty: 5, sets: 3, reps: 15, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Sandalyeye dokunup hemen kalkın, dinlenmeden tekrarlayın.', biomechanics: 'Fonksiyonel bacak dayanıklılığı.', safetyFlags: ['Denge'], equipment: ['Sandalye'], primaryMuscles: ['Legs'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e7', code: 'CV-07', title: 'Shadow Boxing', titleTr: 'Gölge Boksu', category: 'Cardiovascular', difficulty: 4, sets: 3, reps: 60, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Ayakta hafif tempo ile boşluğa yumruk atın.', biomechanics: 'Rotasyonel gövde kontrolü ve aerobik.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Core', 'Shoulders'], rehabPhase: 'Kronik', movementPlane: 'Transverse', tempo: 'Rhythmic', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e8', code: 'CV-08', title: 'Walking Lunges', titleTr: 'Yürüyerek Lunge', category: 'Cardiovascular', difficulty: 7, sets: 2, reps: 20, restPeriod: 60, visualStyle: '4K-Render', description: 'İleri doğru lunge yaparak yürüyün.', biomechanics: 'Dinamik bacak kuvveti ve denge.', safetyFlags: ['Diz Ağrısı'], equipment: ['Yok'], primaryMuscles: ['Quads', 'Glutes'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430e9', code: 'CV-09', title: 'Diaphragmatic Breathing', titleTr: 'Diyafram Solunumu', category: 'Cardiovascular', difficulty: 1, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Internal-Organ', description: 'Sırtüstü, bir el göğüste bir el karında. Sadece karındaki el kalkacak şekilde nefes alın.', biomechanics: 'Parasempatik aktivasyon ve akciğer kapasitesi.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Diaphragm'], rehabPhase: 'Akut', movementPlane: 'N/A', tempo: '4-2-6', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'aba7b811-9dad-11d1-80b4-00c04fd430f0', code: 'CV-10', title: 'Wall Chest Expansion', titleTr: 'Duvar Göğüs Açma', category: 'Cardiovascular', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Köşede kollar açık bekleyerek göğüs kafesini esnetin ve derin nefes alın.', biomechanics: 'Torakal mobilite ve solunum kapasitesi.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Pectorals'], rehabPhase: 'Akut', movementPlane: 'Frontal', tempo: 'Hold', secondaryMuscles: ['Intercostals'], isMotion: true, targetRpe: 2 },

  // ==========================================
  // 7. POST-OP (CERRAHİ SONRASI) - 10 ITEMS
  // ==========================================
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f1', code: 'PO-01', title: 'Quad Sets (Superior)', titleTr: 'Quad Set (Üstün)', category: 'Post-Op', difficulty: 1, sets: 4, reps: 10, restPeriod: 30, visualStyle: 'Muscle-Map', description: 'Diz altına havlu rulo koyun. Dizi bastırarak topuğu hafifçe yerden kesin (VMO aktivasyonu).', biomechanics: 'Quadriceps inhibisyonunu kırma.', safetyFlags: [], equipment: ['Havlu'], primaryMuscles: ['Quadriceps'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '5s Hold', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f2', code: 'PO-02', title: 'Heel Props', titleTr: 'Topuk Yükseltme', category: 'Post-Op', difficulty: 2, sets: 3, reps: 5, restPeriod: 30, visualStyle: 'X-Ray', description: 'Sadece topuk bir yastık üzerindeyken bacağı boşlukta bırakın. Yerçekimi ile dizin düzleşmesini sağlayın.', biomechanics: 'Pasif terminal diz ekstansiyonu kazanımı (ACL sonrası kritik).', safetyFlags: ['Aşırı Ağrı'], equipment: ['Yastık'], primaryMuscles: ['Gravity'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2 min Hold', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f3', code: 'PO-03', title: 'Heel Slides (Assisted)', titleTr: 'Topuk Kaydırma (Kemerle)', category: 'Post-Op', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Ayağa bir kemer/havlu bağlayarak ellerinizle çekip dizi bükün.', biomechanics: 'Pasif/Aktif-Yardımlı diz fleksiyonu.', safetyFlags: ['Dikiş Gerginliği'], equipment: ['Kemer'], primaryMuscles: ['Hamstrings'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f4', code: 'PO-04', title: 'Patellar Mobilization', titleTr: 'Patella Mobilizasyonu', category: 'Post-Op', difficulty: 1, sets: 2, reps: 5, restPeriod: 30, visualStyle: 'Close-Up', description: 'Bacak gevşekken diz kapağını elinizle yukarı-aşağı ve sağa-sola nazikçe oynatın.', biomechanics: 'Yapışıklık (adezyon) önleme.', safetyFlags: ['Taze Yara'], equipment: ['Yok'], primaryMuscles: ['Patella'], rehabPhase: 'Akut', movementPlane: 'Multi-Planar', tempo: 'Gentle', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f5', code: 'PO-05', title: 'Straight Leg Raise (SLR)', titleTr: 'Düz Bacak Kaldırma', category: 'Post-Op', difficulty: 3, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'X-Ray', description: 'Dizi hiç bükmeden ("kilitli") bacağı 45 derece kaldırın. Quad lag (diz çökmesi) olmamalı.', biomechanics: 'Kalça fleksör ve izometrik quad kuvveti.', safetyFlags: ['Quad Lag'], equipment: ['Yok'], primaryMuscles: ['Rectus Femoris'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f6', code: 'PO-06', title: 'Ankle Pumps', titleTr: 'Ayak Bileği Pompası', category: 'Post-Op', difficulty: 1, sets: 5, reps: 20, restPeriod: 20, visualStyle: 'Vein-Flow', description: 'Ayak bileğini hızlıca kendinize çekip itin.', biomechanics: 'Venöz dönüşü artırma ve DVT önleme.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Calves'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f7', code: 'PO-07', title: 'Short Arc Quads', titleTr: 'Kısa Ark Quad', category: 'Post-Op', difficulty: 3, sets: 3, reps: 12, restPeriod: 30, visualStyle: '4K-Render', description: 'Diz altında büyük bir rulo varken topuğu yerden kaldırıp dizi kilitleyin.', biomechanics: 'Son derece ekstansiyon kuvveti.', safetyFlags: [], equipment: ['Foam Roller'], primaryMuscles: ['VMO'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '2-3-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f8', code: 'PO-08', title: 'Assisted Shoulder Flexion', titleTr: 'Sopalı Omuz Fleksiyonu', category: 'Post-Op', difficulty: 2, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Schematic', description: 'Sırtüstü yatarken bir sopa yardımıyla sağlam kol ameliyatlı kolu yukarı itsin.', biomechanics: 'Aktif-Yardımlı omuz eklem hareket açıklığı.', safetyFlags: ['Ağrı Eşiği'], equipment: ['Sopa'], primaryMuscles: ['Deltoid'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd430f9', code: 'PO-09', title: 'Pendulum (Codman)', titleTr: 'Sarkaç Egzersizi', category: 'Post-Op', difficulty: 1, sets: 3, reps: 30, restPeriod: 30, visualStyle: 'X-Ray', description: 'Gövde öne eğik, kolu serbest bırakın ve vücut hareketiyle sallanmasını sağlayın.', biomechanics: 'Glenohumeral eklem distraksiyonu ve ağrı modülasyonu.', safetyFlags: [], equipment: ['Masa (Destek)'], primaryMuscles: ['Gravity'], rehabPhase: 'Akut', movementPlane: 'Circular', tempo: 'Fluid', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'bba7b811-9dad-11d1-80b4-00c04fd43100', code: 'PO-10', title: 'Mini Squat (Supported)', titleTr: 'Destekli Mini Squat', category: 'Post-Op', difficulty: 4, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Bir yere tutunarak sadece 30-45 derece çöküp kalkın.', biomechanics: 'Erken dönem kapalı kinetik zincir yüklenmesi.', safetyFlags: ['Tam Çökme Yasak'], equipment: ['Sandalye'], primaryMuscles: ['Quads'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: ['Glutes'], isMotion: true, targetRpe: 5 }
];
