
import { Exercise } from './types.ts';

/**
 * PHYSIOCORE MASTER CLINICAL LIBRARY v12.2 (COMPLETE 70 ITEMS)
 * 7 Categories x 10 Exercises = 70 Professional Records.
 */
export const SEED_EXERCISES: Exercise[] = [
  // --- 1. SPINE (OMURGA) ---
  {
    id: 'sp-01', code: 'SP-01', title: 'McKenzie Prone Press-up', titleTr: 'McKenzie Yüzüstü Doğrulma',
    category: 'Spine', difficulty: 3, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion',
    description: 'Yüzüstü yatın, kollarınızla gövdenizi kalçayı yerden ayırmadan yukarı itin. Bel bölgesinde "santralizasyon" hedeflenir.',
    biomechanics: 'L4-L5 anterior disk migrasyonu.', safetyFlags: ['Spondylolisthesis'], equipment: ['Mat'], primaryMuscles: ['Erector Spinae'],
    rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-2-2', secondaryMuscles: ['Triceps'], isMotion: true, targetRpe: 4
  },
  {
    id: 'sp-02', code: 'SP-02', title: 'Bird-Dog Precision', titleTr: 'Bird-Dog (Stabilizasyon)',
    category: 'Spine', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'X-Ray',
    description: 'Dört ayak üzerinde nötr omurga pozisyonunu koruyarak çapraz kol ve bacağı uzatın.',
    biomechanics: 'Multifidus izometrik aktivasyonu.', safetyFlags: ['Denge Kaybı'], equipment: ['Mat'], primaryMuscles: ['Multifidus'],
    rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '3-3-3', secondaryMuscles: ['Gluteus Max'], isMotion: true, targetRpe: 6
  },
  { id: 'sp-03', code: 'SP-03', title: 'Open Book Stretch', titleTr: 'Open Book (Torakal)', category: 'Spine', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Yan yatışta üstteki kolu geriye açarak göğsü esnetin.', biomechanics: 'Torakal rotasyon.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Thoracic Paraspinals'], rehabPhase: 'Akut', movementPlane: 'Transverse', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'sp-04', code: 'SP-04', title: 'Chin Tucks', titleTr: 'Chin Tuck', category: 'Spine', difficulty: 2, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'X-Ray', description: 'Başınızı geriye doğru çekerek gıdı çıkarın.', biomechanics: 'Deep Neck Flexor aktivasyonu.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Longus Colli'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '3-5-3', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'sp-05', code: 'SP-05', title: 'Cat-Camel', titleTr: 'Kedi-Deve', category: 'Spine', difficulty: 3, sets: 3, reps: 10, restPeriod: 30, visualStyle: '4K-Render', description: 'Omurgayı segment segment bükün ve düzleştirin.', biomechanics: 'Vertebral mobilizasyon.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Multifidus'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '4-0-4', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: 'sp-06', code: 'SP-06', title: 'Sciatic Nerve Flossing', titleTr: 'Siyatik Sinir Kaydırma', category: 'Spine', difficulty: 4, sets: 2, reps: 15, restPeriod: 45, visualStyle: 'Nerve-Highlight', description: 'Sırtüstü bacağı kaldırıp ayak bileğini pompalayın.', biomechanics: 'Nörodinamik mobilizasyon.', safetyFlags: ['Akut Ağrı'], equipment: ['Yok'], primaryMuscles: ['Neural Tissue'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Fluid', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'sp-07', code: 'SP-07', title: 'Wall Angels', titleTr: 'Duvar Meleği', category: 'Spine', difficulty: 5, sets: 3, reps: 12, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Duvara yaslanıp kolları W-I şeklinde kaydırın.', biomechanics: 'Torakal ekstansiyon.', safetyFlags: ['Omuz İmpingement'], equipment: ['Duvar'], primaryMuscles: ['Lower Trapezius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: '3-2-3', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'sp-08', code: 'SP-08', title: 'Jefferson Curl (Light)', titleTr: 'Jefferson Curl', category: 'Spine', difficulty: 7, sets: 3, reps: 8, restPeriod: 60, visualStyle: '4K-Render', description: 'Ayakta omurgayı boyundan başlayarak yavaşça aşağı yuvarlayın.', biomechanics: 'Posterior zincir esnekliği.', safetyFlags: ['Osteoporoz'], equipment: ['Hafif Ağırlık'], primaryMuscles: ['Erector Spinae'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '5-2-5', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'sp-09', code: 'SP-09', title: 'Pallof Press (Kneeling)', titleTr: 'Dizüstü Pallof', category: 'Spine', difficulty: 6, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Dizüstü pozisyonda yan dirence karşı elleri ileri itin.', biomechanics: 'Anti-rotasyonel stabilite.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['Obliques'], rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: '2-3-2', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'sp-10', code: 'SP-10', title: 'Child\'s Pose Flow', titleTr: 'Çocuk Pozu Akışı', category: 'Spine', difficulty: 3, sets: 3, reps: 8, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Topuklara oturma pozisyonundan öne doğru esneyin.', biomechanics: 'Lumbar fleksiyon.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Spinals'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Flow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },

  // --- 2. LOWER LIMB (ALT EKSTREMİTE) ---
  { id: 'll-01', code: 'LL-01', title: 'Nordic Hamstring Curl', titleTr: 'Nordic Hamstring', category: 'Lower Limb', difficulty: 9, sets: 3, reps: 6, restPeriod: 90, visualStyle: 'Cinematic-Motion', description: 'Dizler sabitken gövdeyi öne bırakın.', biomechanics: 'Eksentrik hamstring kuvveti.', safetyFlags: ['Akut Yırtık'], equipment: ['Sabit Destek'], primaryMuscles: ['Hamstrings'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 9 },
  { id: 'll-02', code: 'LL-02', title: 'Single Leg RDL', titleTr: 'Tek Ayak RDL', category: 'Lower Limb', difficulty: 7, sets: 3, reps: 10, restPeriod: 60, visualStyle: '4K-Render', description: 'Tek ayak üzerinde T pozisyonu.', biomechanics: 'Dinamik kalça stabilitesi.', safetyFlags: ['Denge'], equipment: ['Yok'], primaryMuscles: ['Glutes'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'll-03', code: 'LL-03', title: 'Goblet Squat', titleTr: 'Goblet Squat', category: 'Lower Limb', difficulty: 5, sets: 4, reps: 12, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Ağırlığı göğüste tutarak çökün.', biomechanics: 'Derin diz fleksiyonu.', safetyFlags: ['Menisküs'], equipment: ['Dumbbell'], primaryMuscles: ['Quads'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: '3-1-1', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'll-04', code: 'LL-04', title: 'Monster Walk', titleTr: 'Monster Walk', category: 'Lower Limb', difficulty: 4, sets: 3, reps: 20, restPeriod: 45, visualStyle: 'X-Ray', description: 'Bantla yan yürüyüş.', biomechanics: 'Gluteus Medius izolasyonu.', safetyFlags: [], equipment: ['Loop Band'], primaryMuscles: ['Glute Medius'], rehabPhase: 'Sub-Akut', movementPlane: 'Frontal', tempo: 'Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'll-05', code: 'LL-05', title: 'Tibialis Raises', titleTr: 'Tibialis Kaldırma', category: 'Lower Limb', difficulty: 3, sets: 3, reps: 20, restPeriod: 30, visualStyle: 'Schematic', description: 'Duvara yaslanıp ayak ucunu kaldırın.', biomechanics: 'Shin splint önleme.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Tibialis Ant'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '1-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'll-06', code: 'LL-06', title: 'Bulgarian Split Squat', titleTr: 'Bulgar Squat', category: 'Lower Limb', difficulty: 8, sets: 3, reps: 10, restPeriod: 90, visualStyle: 'Cinematic-Motion', description: 'Arka ayak yüksekte tek bacak squat.', biomechanics: 'Unilateral kuvvet.', safetyFlags: ['Diz Ağrısı'], equipment: ['Bench'], primaryMuscles: ['Quads'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: '3-1-1', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'll-07', code: 'LL-07', title: 'Copenhagen Plank', titleTr: 'Copenhagen Plank', category: 'Lower Limb', difficulty: 8, sets: 3, reps: 30, restPeriod: 60, visualStyle: 'Muscle-Map', description: 'Yan plankte üst bacakla tutunma.', biomechanics: 'Adductor kuvveti.', safetyFlags: ['Kasık Ağrısı'], equipment: ['Bench'], primaryMuscles: ['Adductors'], rehabPhase: 'Performans', movementPlane: 'Frontal', tempo: 'Iso', secondaryMuscles: [], isMotion: true, targetRpe: 9 },
  { id: 'll-08', code: 'LL-08', title: 'Terminal Knee Ext (TKE)', titleTr: 'TKE (Diz Kilitleme)', category: 'Lower Limb', difficulty: 2, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'X-Ray', description: 'Bantla dizi kilitleme.', biomechanics: 'VMO aktivasyonu.', safetyFlags: [], equipment: ['Bant'], primaryMuscles: ['VMO'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: '2-3-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'll-09', code: 'LL-09', title: 'Step Downs', titleTr: 'Step Down', category: 'Lower Limb', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Basamaktan yavaş inme.', biomechanics: 'Eksentrik quad kontrolü.', safetyFlags: ['Patella'], equipment: ['Step'], primaryMuscles: ['Quads'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'll-10', code: 'LL-10', title: 'Glute Bridge March', titleTr: 'Köprüde Yürüyüş', category: 'Lower Limb', difficulty: 4, sets: 3, reps: 20, restPeriod: 45, visualStyle: '4K-Render', description: 'Köprüde tek tek ayak kaldırma.', biomechanics: 'Pelvik stabilite.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Glutes'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'March', secondaryMuscles: [], isMotion: true, targetRpe: 5 },

  // --- 3. UPPER LIMB (ÜST EKSTREMİTE) ---
  { id: 'ul-01', code: 'UL-01', title: 'Y-T-W-L Series', titleTr: 'Y-T-W-L Serisi', category: 'Upper Limb', difficulty: 4, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Muscle-Map', description: 'Kolları harf şekillerine getirin.', biomechanics: 'Scapular stabilizasyon.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Trapezius'], rehabPhase: 'Sub-Akut', movementPlane: 'Multi', tempo: '2-2-2', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'ul-02', code: 'UL-02', title: 'Serratus Wall Slides', titleTr: 'Duvar Kaydırma', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 12, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Ön kollarla duvarda kayma.', biomechanics: 'Serratus anterior.', safetyFlags: [], equipment: ['Band'], primaryMuscles: ['Serratus Ant'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'ul-03', code: 'UL-03', title: 'Median Nerve Glide', titleTr: 'Median Sinir Kaydırma', category: 'Upper Limb', difficulty: 2, sets: 2, reps: 10, restPeriod: 30, visualStyle: 'Nerve-Highlight', description: 'Sinir mobilizasyonu.', biomechanics: 'Nörodinamik.', safetyFlags: ['Uyuşma'], equipment: ['Yok'], primaryMuscles: ['Nerve'], rehabPhase: 'Akut', movementPlane: 'Frontal', tempo: 'Flow', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: 'ul-04', code: 'UL-04', title: 'Face Pulls', titleTr: 'Face Pull', category: 'Upper Limb', difficulty: 5, sets: 3, reps: 15, restPeriod: 45, visualStyle: '4K-Render', description: 'Bandı yüze çekme.', biomechanics: 'Dış rotasyon.', safetyFlags: [], equipment: ['Band'], primaryMuscles: ['Rear Delt'], rehabPhase: 'Kronik', movementPlane: 'Transverse', tempo: '2-1-2', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'ul-05', code: 'UL-05', title: 'Iso Shoulder Abd', titleTr: 'İzometrik Omuz Abd.', category: 'Upper Limb', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Duvara yan baskı.', biomechanics: 'Statik deltoid.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Deltoid'], rehabPhase: 'Akut', movementPlane: 'Frontal', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'ul-06', code: 'UL-06', title: 'Farmers Carry', titleTr: 'Çiftçi Yürüyüşü', category: 'Upper Limb', difficulty: 6, sets: 3, reps: 60, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Ağırlıkla yürüme.', biomechanics: 'Grip & Core.', safetyFlags: [], equipment: ['KB'], primaryMuscles: ['Forearm'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Walk', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'ul-07', code: 'UL-07', title: 'Doorway Stretch', titleTr: 'Kapı Germe', category: 'Upper Limb', difficulty: 1, sets: 2, reps: 30, restPeriod: 20, visualStyle: 'X-Ray', description: 'Pektoral germe.', biomechanics: 'Pec Major.', safetyFlags: ['Anterior Ağrı'], equipment: ['Kapı'], primaryMuscles: ['Pectorals'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Static', secondaryMuscles: [], isMotion: true, targetRpe: 2 },
  { id: 'ul-08', code: 'UL-08', title: 'Eccentric Wrist Ext', titleTr: 'Eksentrik Bilek', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'Close-Up', description: 'Yavaş indirme.', biomechanics: 'Tenisçi dirseği.', safetyFlags: [], equipment: ['DB'], primaryMuscles: ['Extensors'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'ul-09', code: 'UL-09', title: 'PNF D2 Flexion', titleTr: 'PNF D2', category: 'Upper Limb', difficulty: 5, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Kılıç çekme hareketi.', biomechanics: 'Fonksiyonel patern.', safetyFlags: [], equipment: ['Band'], primaryMuscles: ['Rotator Cuff'], rehabPhase: 'Kronik', movementPlane: 'Diagonal', tempo: 'Fluid', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'ul-10', code: 'UL-10', title: 'Scapular Push-ups', titleTr: 'Skapular Şınav', category: 'Upper Limb', difficulty: 3, sets: 3, reps: 15, restPeriod: 30, visualStyle: 'Schematic', description: 'Sadece kürek kemiği hareketi.', biomechanics: 'Serratus izolasyonu.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Serratus'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 4 },

  // --- 4. STABILITY (STABILIZASYON) ---
  { id: 'st-01', code: 'ST-01', title: 'Stir the Pot', titleTr: 'Stir the Pot', category: 'Stability', difficulty: 8, sets: 3, reps: 10, restPeriod: 60, visualStyle: '4K-Render', description: 'Top üzerinde plank daireleri.', biomechanics: 'Anti-extension.', safetyFlags: ['Bel'], equipment: ['Ball'], primaryMuscles: ['Core'], rehabPhase: 'Performans', movementPlane: 'Circular', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 9 },
  { id: 'st-02', code: 'ST-02', title: 'Dead Bug', titleTr: 'Dead Bug', category: 'Stability', difficulty: 6, sets: 3, reps: 12, restPeriod: 45, visualStyle: 'X-Ray', description: 'Sırtüstü çapraz kol bacak.', biomechanics: 'Anterior core.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Abs'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-0-3', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'st-03', code: 'ST-03', title: 'Suitcase Carry', titleTr: 'Bavul Taşıma', category: 'Stability', difficulty: 5, sets: 3, reps: 60, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Tek el yükle yürüme.', biomechanics: 'Anti-lateral flexion.', safetyFlags: [], equipment: ['KB'], primaryMuscles: ['Obliques'], rehabPhase: 'Kronik', movementPlane: 'Frontal', tempo: 'Walk', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'st-04', code: 'ST-04', title: 'Pallof Press', titleTr: 'Pallof Press', category: 'Stability', difficulty: 5, sets: 3, reps: 12, restPeriod: 45, visualStyle: '4K-Render', description: 'Yan dirence karşı itiş.', biomechanics: 'Anti-rotation.', safetyFlags: [], equipment: ['Band'], primaryMuscles: ['Obliques'], rehabPhase: 'Sub-Akut', movementPlane: 'Transverse', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'st-05', code: 'ST-05', title: 'Side Plank Rotations', titleTr: 'Yan Plank Rotasyon', category: 'Stability', difficulty: 7, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Yan plankte dönme.', biomechanics: 'Rotasyonel kontrol.', safetyFlags: ['Omuz'], equipment: ['Mat'], primaryMuscles: ['Obliques'], rehabPhase: 'Kronik', movementPlane: 'Multi', tempo: 'Controlled', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'st-06', code: 'ST-06', title: 'Single Leg Balance', titleTr: 'Tek Ayak Denge', category: 'Stability', difficulty: 4, sets: 3, reps: 30, restPeriod: 30, visualStyle: 'X-Ray', description: 'Tek ayak duruş.', biomechanics: 'Propriyosepsiyon.', safetyFlags: ['Düşme'], equipment: ['Yok'], primaryMuscles: ['Ankle'], rehabPhase: 'Sub-Akut', movementPlane: 'Static', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'st-07', code: 'ST-07', title: 'Bear Crawl', titleTr: 'Ayı Yürüyüşü', category: 'Stability', difficulty: 7, sets: 3, reps: 20, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Dört ayak, dizler havada yürüme.', biomechanics: 'Dinamik core.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Core'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Crawl', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'st-08', code: 'ST-08', title: 'Bosu Squat', titleTr: 'Bosu Squat', category: 'Stability', difficulty: 6, sets: 3, reps: 15, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Dengesiz zeminde squat.', biomechanics: 'Nöromusküler.', safetyFlags: ['Düşme'], equipment: ['Bosu'], primaryMuscles: ['Legs'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'st-09', code: 'ST-09', title: 'Turkish Get Up (Half)', titleTr: 'Yarım TGU', category: 'Stability', difficulty: 8, sets: 3, reps: 5, restPeriod: 90, visualStyle: '4K-Render', description: 'Yerden doğrulma.', biomechanics: 'Full body.', safetyFlags: ['Omuz'], equipment: ['KB'], primaryMuscles: ['Full Body'], rehabPhase: 'Performans', movementPlane: 'Multi', tempo: 'Flow', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'st-10', code: 'ST-10', title: 'RKC Plank', titleTr: 'RKC Plank', category: 'Stability', difficulty: 9, sets: 4, reps: 15, restPeriod: 60, visualStyle: 'Muscle-Map', description: 'Maksimum gerilimli plank.', biomechanics: 'High tension core.', safetyFlags: ['Tansiyon'], equipment: ['Mat'], primaryMuscles: ['Abs'], rehabPhase: 'Performans', movementPlane: 'Iso', tempo: 'Max', secondaryMuscles: [], isMotion: true, targetRpe: 10 },

  // --- 5. NEUROLOGICAL (NÖROLOJİK) ---
  { id: 'ne-01', code: 'NE-01', title: 'Mirror Therapy', titleTr: 'Ayna Terapisi', category: 'Neurological', difficulty: 2, sets: 3, reps: 5, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Ayna ile görsel illüzyon.', biomechanics: 'Nöroplastisite.', safetyFlags: [], equipment: ['Ayna'], primaryMuscles: ['Brain'], rehabPhase: 'Akut', movementPlane: 'Visual', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'ne-02', code: 'NE-02', title: 'Clock Reach', titleTr: 'Saat Yönü Uzanma', category: 'Neurological', difficulty: 4, sets: 2, reps: 5, restPeriod: 45, visualStyle: 'Floor-Grid', description: 'Tek ayak üzerinde saat yönlerine uzanma.', biomechanics: 'Dinamik denge.', safetyFlags: ['Düşme'], equipment: ['Yok'], primaryMuscles: ['Legs'], rehabPhase: 'Sub-Akut', movementPlane: 'Multi', tempo: 'Control', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'ne-03', code: 'NE-03', title: 'Dual Task Walk', titleTr: 'Çift Görevli Yürüyüş', category: 'Neurological', difficulty: 6, sets: 1, reps: 60, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Yürürken sayma.', biomechanics: 'Kognitif-Motor.', safetyFlags: ['Düşme'], equipment: ['Yok'], primaryMuscles: ['Brain'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Walk', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'ne-04', code: 'NE-04', title: 'Sit-to-Stand', titleTr: 'Otur-Kalk', category: 'Neurological', difficulty: 4, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'X-Ray', description: 'Desteksiz kalkış.', biomechanics: 'Fonksiyonel kuvvet.', safetyFlags: ['Denge'], equipment: ['Sandalye'], primaryMuscles: ['Legs'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Power', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'ne-05', code: 'NE-05', title: 'Tandem Stance', titleTr: 'Tandem Duruş', category: 'Neurological', difficulty: 5, sets: 3, reps: 30, restPeriod: 30, visualStyle: 'Schematic', description: 'Göz kapalı sıralı duruş.', biomechanics: 'Vestibüler.', safetyFlags: ['Düşme'], equipment: ['Duvar'], primaryMuscles: ['Postural'], rehabPhase: 'Kronik', movementPlane: 'Static', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'ne-06', code: 'NE-06', title: 'PNF D1', titleTr: 'PNF D1', category: 'Neurological', difficulty: 4, sets: 3, reps: 10, restPeriod: 30, visualStyle: '4K-Render', description: 'Emniyet kemeri hareketi.', biomechanics: 'Diyagonal.', safetyFlags: [], equipment: ['Band'], primaryMuscles: ['Shoulder'], rehabPhase: 'Sub-Akut', movementPlane: 'Diagonal', tempo: 'Fluid', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'ne-07', code: 'NE-07', title: 'Frenkel Ex', titleTr: 'Frenkel Egzersizi', category: 'Neurological', difficulty: 3, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Schematic', description: 'Koordinasyon.', biomechanics: 'Ataksi.', safetyFlags: [], equipment: ['Mat'], primaryMuscles: ['Legs'], rehabPhase: 'Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'ne-08', code: 'NE-08', title: 'Weight Shift', titleTr: 'Ağırlık Aktarma', category: 'Neurological', difficulty: 3, sets: 3, reps: 20, restPeriod: 30, visualStyle: 'Center-of-Pressure', description: 'Sway kontrol.', biomechanics: 'Denge stratejisi.', safetyFlags: ['Düşme'], equipment: ['Yok'], primaryMuscles: ['Ankle'], rehabPhase: 'Sub-Akut', movementPlane: 'Combined', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'ne-09', code: 'NE-09', title: 'Scapular PNF', titleTr: 'Skapular PNF', category: 'Neurological', difficulty: 3, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Muscle-Map', description: 'Kürek kemiği mobilizasyonu.', biomechanics: 'Proksimal stabilite.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Scapula'], rehabPhase: 'Akut', movementPlane: 'Diagonal', tempo: 'Control', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'ne-10', code: 'NE-10', title: 'Balloon Taps', titleTr: 'Balon Sektirme', category: 'Neurological', difficulty: 4, sets: 2, reps: 60, restPeriod: 30, visualStyle: 'Cinematic-Motion', description: 'Reaktif denge.', biomechanics: 'El-Göz.', safetyFlags: ['Düşme'], equipment: ['Balon'], primaryMuscles: ['Full Body'], rehabPhase: 'Sub-Akut', movementPlane: 'Random', tempo: 'Reactive', secondaryMuscles: [], isMotion: true, targetRpe: 5 },

  // --- 6. CARDIOVASCULAR (KARDİYOVASKÜLER) ---
  { id: 'cv-01', code: 'CV-01', title: 'Recumbent Bike', titleTr: 'Yatay Bisiklet', category: 'Cardiovascular', difficulty: 4, sets: 1, reps: 15, restPeriod: 0, visualStyle: 'Cinematic-Motion', description: 'İnterval sürüş.', biomechanics: 'Aerobik.', safetyFlags: [], equipment: ['Bisiklet'], primaryMuscles: ['Legs'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Interval', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'cv-02', code: 'CV-02', title: 'Arm Ergometer', titleTr: 'Kol Ergometresi', category: 'Cardiovascular', difficulty: 3, sets: 1, reps: 10, restPeriod: 0, visualStyle: 'Cinematic-Motion', description: 'El bisikleti.', biomechanics: 'Üst vücut aerobik.', safetyFlags: [], equipment: ['UBE'], primaryMuscles: ['Arms'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Steady', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'cv-03', code: 'CV-03', title: 'Seated Marching', titleTr: 'Oturarak Adım', category: 'Cardiovascular', difficulty: 2, sets: 3, reps: 60, restPeriod: 30, visualStyle: 'X-Ray', description: 'Hızlı diz çekme.', biomechanics: 'Kalça fleksör.', safetyFlags: [], equipment: ['Sandalye'], primaryMuscles: ['Hip Flexors'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'cv-04', code: 'CV-04', title: 'Box Step Ups', titleTr: 'Kutuya Çıkış', category: 'Cardiovascular', difficulty: 5, sets: 3, reps: 20, restPeriod: 45, visualStyle: '4K-Render', description: 'Step tahtası.', biomechanics: 'Bacak kuvveti.', safetyFlags: ['Diz'], equipment: ['Step'], primaryMuscles: ['Legs'], rehabPhase: 'Kronik', movementPlane: 'Sagittal', tempo: 'Rhythm', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'cv-05', code: 'CV-05', title: 'Battle Ropes', titleTr: 'Halat (Oturarak)', category: 'Cardiovascular', difficulty: 6, sets: 3, reps: 30, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Halat sallama.', biomechanics: 'Anaerobik.', safetyFlags: ['Omuz'], equipment: ['Rope'], primaryMuscles: ['Arms'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Max', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'cv-06', code: 'CV-06', title: 'Sit-to-Stand Interval', titleTr: 'Otur-Kalk İnterval', category: 'Cardiovascular', difficulty: 5, sets: 3, reps: 15, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Hızlı tekrar.', biomechanics: 'Bacak day.', safetyFlags: ['Denge'], equipment: ['Sandalye'], primaryMuscles: ['Legs'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 7 },
  { id: 'cv-07', code: 'CV-07', title: 'Shadow Boxing', titleTr: 'Gölge Boksu', category: 'Cardiovascular', difficulty: 4, sets: 3, reps: 60, restPeriod: 45, visualStyle: 'Cinematic-Motion', description: 'Boşluğa yumruk.', biomechanics: 'Rotasyon.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Core'], rehabPhase: 'Kronik', movementPlane: 'Transverse', tempo: 'Rhythm', secondaryMuscles: [], isMotion: true, targetRpe: 6 },
  { id: 'cv-08', code: 'CV-08', title: 'Walking Lunges', titleTr: 'Yürüyerek Lunge', category: 'Cardiovascular', difficulty: 7, sets: 2, reps: 20, restPeriod: 60, visualStyle: '4K-Render', description: 'Lunge yürüyüşü.', biomechanics: 'Dinamik kuvvet.', safetyFlags: ['Diz'], equipment: ['Yok'], primaryMuscles: ['Legs'], rehabPhase: 'Performans', movementPlane: 'Sagittal', tempo: 'Walk', secondaryMuscles: [], isMotion: true, targetRpe: 8 },
  { id: 'cv-09', code: 'CV-09', title: 'Diaphragm Breath', titleTr: 'Diyafram Solunumu', category: 'Cardiovascular', difficulty: 1, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Internal-Organ', description: 'Derin nefes.', biomechanics: 'Solunum.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Diaphragm'], rehabPhase: 'Akut', movementPlane: 'N/A', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'cv-10', code: 'CV-10', title: 'Chest Expansion', titleTr: 'Göğüs Açma', category: 'Cardiovascular', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Köşede esneme.', biomechanics: 'Kapasite.', safetyFlags: [], equipment: ['Duvar'], primaryMuscles: ['Pec'], rehabPhase: 'Akut', movementPlane: 'Frontal', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 2 },

  // --- 7. POST-OP (CERRAHİ SONRASI) ---
  { id: 'po-01', code: 'PO-01', title: 'Quad Set', titleTr: 'Quad Set', category: 'Post-Op', difficulty: 1, sets: 4, reps: 10, restPeriod: 30, visualStyle: 'Muscle-Map', description: 'Dizi bastırma.', biomechanics: 'VMO.', safetyFlags: [], equipment: ['Havlu'], primaryMuscles: ['Quads'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Iso', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'po-02', code: 'PO-02', title: 'Heel Props', titleTr: 'Topuk Yükseltme', category: 'Post-Op', difficulty: 2, sets: 3, reps: 5, restPeriod: 30, visualStyle: 'X-Ray', description: 'Pasif ekstansiyon.', biomechanics: 'Ekstansiyon.', safetyFlags: ['Ağrı'], equipment: ['Yastık'], primaryMuscles: ['Gravity'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Hold', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'po-03', code: 'PO-03', title: 'Heel Slide', titleTr: 'Topuk Kaydırma', category: 'Post-Op', difficulty: 2, sets: 3, reps: 10, restPeriod: 30, visualStyle: 'Schematic', description: 'Aktif yardımlı bükme.', biomechanics: 'Fleksiyon.', safetyFlags: ['Dikiş'], equipment: ['Kemer'], primaryMuscles: ['Hamstring'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'po-04', code: 'PO-04', title: 'Patella Mob', titleTr: 'Patella Mobilizasyonu', category: 'Post-Op', difficulty: 1, sets: 2, reps: 5, restPeriod: 30, visualStyle: 'Close-Up', description: 'Kapak oynatma.', biomechanics: 'Adezyon.', safetyFlags: ['Yara'], equipment: ['Yok'], primaryMuscles: ['Patella'], rehabPhase: 'Akut', movementPlane: 'Multi', tempo: 'Gentle', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'po-05', code: 'PO-05', title: 'SLR', titleTr: 'Düz Bacak Kaldırma', category: 'Post-Op', difficulty: 3, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'X-Ray', description: 'Kilitli diz kaldırma.', biomechanics: 'Kalça flx.', safetyFlags: ['Lag'], equipment: ['Yok'], primaryMuscles: ['Quads'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '3-1-3', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
  { id: 'po-06', code: 'PO-06', title: 'Ankle Pumps', titleTr: 'Ayak Pompası', category: 'Post-Op', difficulty: 1, sets: 5, reps: 20, restPeriod: 20, visualStyle: 'Vein-Flow', description: 'Dolaşım.', biomechanics: 'DVT önleme.', safetyFlags: [], equipment: ['Yok'], primaryMuscles: ['Calf'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Fast', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'po-07', code: 'PO-07', title: 'Short Arc Quad', titleTr: 'Kısa Ark Quad', category: 'Post-Op', difficulty: 3, sets: 3, reps: 12, restPeriod: 30, visualStyle: '4K-Render', description: 'Rulo üzerinden kaldırma.', biomechanics: 'Terminal ext.', safetyFlags: [], equipment: ['Rulo'], primaryMuscles: ['VMO'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: '2-3-2', secondaryMuscles: [], isMotion: true, targetRpe: 4 },
  { id: 'po-08', code: 'PO-08', title: 'Wand Flexion', titleTr: 'Sopalı Fleksiyon', category: 'Post-Op', difficulty: 2, sets: 3, reps: 10, restPeriod: 45, visualStyle: 'Schematic', description: 'Sopa ile omuz kaldırma.', biomechanics: 'Pasif ROM.', safetyFlags: ['Ağrı'], equipment: ['Sopa'], primaryMuscles: ['Shoulder'], rehabPhase: 'Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 3 },
  { id: 'po-09', code: 'PO-09', title: 'Pendulum', titleTr: 'Sarkaç', category: 'Post-Op', difficulty: 1, sets: 3, reps: 30, restPeriod: 30, visualStyle: 'X-Ray', description: 'Omuz sallama.', biomechanics: 'Distraksiyon.', safetyFlags: [], equipment: ['Masa'], primaryMuscles: ['Gravity'], rehabPhase: 'Akut', movementPlane: 'Circular', tempo: 'Fluid', secondaryMuscles: [], isMotion: true, targetRpe: 1 },
  { id: 'po-10', code: 'PO-10', title: 'Mini Squat', titleTr: 'Mini Squat', category: 'Post-Op', difficulty: 4, sets: 3, reps: 10, restPeriod: 60, visualStyle: 'Cinematic-Motion', description: 'Destekli yarım çökme.', biomechanics: 'CKC.', safetyFlags: ['Tam Çökme'], equipment: ['Sandalye'], primaryMuscles: ['Quads'], rehabPhase: 'Sub-Akut', movementPlane: 'Sagittal', tempo: 'Slow', secondaryMuscles: [], isMotion: true, targetRpe: 5 },
];
